import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const cfg = window.SNT_CONFIG || {};
const app = document.getElementById('app');
const toastEl = document.getElementById('toast');
const studentToken = new URLSearchParams(location.search).get(cfg.STUDENT_LINK_PARAM || 's') || (location.hash.startsWith('#s=') ? new URLSearchParams(location.hash.slice(1)).get(cfg.STUDENT_LINK_PARAM || 's') : null);
const teacherLinkToken = new URLSearchParams(location.search).get(cfg.TEACHER_LINK_PARAM || 'teacher') || (location.hash.startsWith('#teacher=') ? new URLSearchParams(location.hash.slice(1)).get(cfg.TEACHER_LINK_PARAM || 'teacher') : null);
const configured = cfg.SUPABASE_URL && !cfg.SUPABASE_URL.includes('YOUR_PROJECT') && cfg.SUPABASE_PUBLISHABLE_KEY && !cfg.SUPABASE_PUBLISHABLE_KEY.includes('YOUR_');
const sb = configured ? createClient(cfg.SUPABASE_URL, cfg.SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: true, autoRefreshToken: true } }) : null;
const BUCKET = 'workbook-files';
let currentTeacher = null;
let studentHubCache = null;

const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const esc = (v='') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const nl2br = (v='') => esc(v).replace(/\n/g,'<br>');
const fmtDate = v => v ? new Date(v + (String(v).length===10 ? 'T00:00:00' : '')).toLocaleDateString('en-ZA',{day:'2-digit',month:'short',year:'numeric'}) : '—';
const fmtDateTime = v => v ? new Date(v).toLocaleString('en-ZA',{dateStyle:'medium',timeStyle:'short'}) : '—';
const todayISO = () => new Date().toISOString().slice(0,10);
const isOverdue = d => !!d && d < todayISO();
const safeFile = n => n.replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-100);
const inferMime = (name='') => /\.pdf$/i.test(name)?'application/pdf':/\.png$/i.test(name)?'image/png':/\.webp$/i.test(name)?'image/webp':/\.hei[cf]$/i.test(name)?'image/heic':/\.jpe?g$/i.test(name)?'image/jpeg':'application/octet-stream';
const uuid = () => crypto.randomUUID();
const token = () => { const b = new Uint8Array(32); crypto.getRandomValues(b); return btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); };
const moneylessPercent = (a,b) => b ? Math.round((Number(a||0)/Number(b))*100) : 0;

function toast(msg, error=false){ toastEl.textContent=msg; toastEl.className='toast show'+(error?' error':''); clearTimeout(toastEl._t); toastEl._t=setTimeout(()=>toastEl.className='toast',3300); }
function downloadBlob(blob,name){ const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1500); }
function csvEscape(v){ const s=String(v??''); return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s; }
function toCSV(rows,cols){ return [cols.join(','),...rows.map(r=>cols.map(c=>csvEscape(r[c])).join(','))].join('\n'); }
function parseLines(v){ return String(v||'').split('\n').map(x=>x.trim()).filter(Boolean); }
function setBusy(btn,busy,label='Working…'){ if(!btn)return; if(busy){btn.dataset.old=btn.textContent;btn.textContent=label;btn.disabled=true}else{btn.textContent=btn.dataset.old||btn.textContent;btn.disabled=false} }
async function signed(path, expires=1800){ const {data,error}=await sb.storage.from(BUCKET).createSignedUrl(path,expires); if(error) throw error; return data.signedUrl; }
async function teacherUpload(file,path){ if(file.size > (cfg.MAX_FILE_MB||10)*1024*1024) throw new Error(`${file.name} is larger than ${cfg.MAX_FILE_MB||10} MB.`); const {error}=await sb.storage.from(BUCKET).upload(path,file,{contentType:file.type||inferMime(file.name),upsert:false}); if(error) throw error; }
async function deleteStorage(path){ if(!path) return; await sb.storage.from(BUCKET).remove([path]); }

function setupScreen(){
  app.innerHTML=`<div class="login"><div class="login-card"><div class="login-logo">SNT</div><h1>Workbook Hub setup</h1><p class="muted">Connect this GitHub site to Supabase first.</p><div class="info-box">Open <span class="code">config.js</span> and enter your Supabase Project URL and Publishable/anon key. Then run <span class="code">supabase/setup.sql</span> and deploy the included student Edge Function.</div><p class="small muted">Full instructions are in README.md.</p></div></div>`;
}

function renderLogin(message=''){
  app.innerHTML=`<div class="login"><form id="loginForm" class="login-card"><div class="login-logo">SNT</div><h1>Teacher workspace</h1><p class="muted">All approved teachers share this workspace.</p>${message?`<div class="error-box">${esc(message)}</div>`:''}<div class="field"><label>Email</label><input name="email" type="email" required autocomplete="username"></div><div class="field"><label>Password</label><input name="password" type="password" required autocomplete="current-password"></div><button class="btn" style="width:100%;margin-top:1rem">Sign in</button><p class="small muted">Learners do not sign in. They use their private workbook link.</p></form></div>`;
  $('#loginForm').onsubmit=async e=>{ e.preventDefault(); const b=e.submitter; setBusy(b,true,'Signing in…'); const f=new FormData(e.currentTarget); const {error}=await sb.auth.signInWithPassword({email:f.get('email'),password:f.get('password')}); if(error){renderLogin(error.message);return;} await startTeacher(); };
}

async function startTeacher(){
  const {data:{session}}=await sb.auth.getSession();
  if(!session){renderLogin();return;}
  const {data,error}=await sb.from('teacher_profiles').select('*').eq('user_id',session.user.id).eq('active',true).maybeSingle();
  if(error || !data){ await sb.auth.signOut(); renderLogin('This account is not an approved active teacher.'); return; }
  currentTeacher={...data,email:session.user.email};
  window.addEventListener('hashchange',renderTeacherRoute);
  await renderTeacherRoute();
}

function teacherShell(body,active='dashboard'){
  const nav=[['dashboard','🏠 Dashboard'],['students','👨‍🎓 Students & links'],['workbooks','📚 Workbooks'],['submissions','📤 Submissions'],['backup','💾 Import / Export']];
  app.innerHTML=`<header class="topbar"><div class="brand"><div class="brand-badge">SNT</div><div>${esc(cfg.APP_NAME||'SNT Workbook Hub')}</div></div><div class="top-actions"><span class="small">${esc(currentTeacher.display_name||currentTeacher.email)}</span><button id="signOut" class="btn ghost sm">Sign out</button></div></header><div class="shell"><aside class="sidebar">${nav.map(([k,l])=>`<button class="navbtn ${active===k?'active':''}" data-nav="${k}">${l}</button>`).join('')}</aside><main class="content">${body}</main></div>`;
  $$('[data-nav]').forEach(b=>b.onclick=()=>location.hash=b.dataset.nav);
  $('#signOut').onclick=async()=>{await sb.auth.signOut();location.hash='';renderLogin();};
}

async function renderTeacherRoute(){
  const raw=location.hash.replace(/^#/,'')||'dashboard';
  const [route,id]=raw.split(':');
  try{
    if(route==='students') return pageStudents();
    if(route==='workbooks') return id?pageWorkbook(id):pageWorkbooks();
    if(route==='submissions') return pageSubmissions();
    if(route==='backup') return pageBackup();
    return pageDashboard();
  }catch(e){ console.error(e); teacherShell(`<div class="error-box">${esc(e.message||String(e))}</div>`,'dashboard'); }
}

async function pageDashboard(){
  const [{count:students},{count:workbooks},{count:activities},{count:submissions},{data:recent}] = await Promise.all([
    sb.from('students').select('*',{count:'exact',head:true}).eq('active',true),
    sb.from('workbooks').select('*',{count:'exact',head:true}).eq('active',true),
    sb.from('activities').select('*',{count:'exact',head:true}),
    sb.from('submissions').select('*',{count:'exact',head:true}),
    sb.from('submissions').select('id,submitted_at,status,score,students(name),activities(title,total_marks,workbooks(title,subject,term))').order('submitted_at',{ascending:false}).limit(8)
  ]);
  teacherShell(`<div class="page-head"><div><h1>Shared teacher workspace</h1><p>Every approved teacher sees and manages the same workbook system.</p></div></div><div class="grid cards"><div class="card"><div class="muted">Active students</div><div class="stat">${students||0}</div></div><div class="card"><div class="muted">Active workbooks</div><div class="stat">${workbooks||0}</div></div><div class="card"><div class="muted">Activities</div><div class="stat">${activities||0}</div></div><div class="card"><div class="muted">Submissions</div><div class="stat">${submissions||0}</div></div></div><div class="card" style="margin-top:1rem"><h2>Recent submissions</h2>${recent?.length?`<div class="table-wrap"><table><thead><tr><th>Student</th><th>Workbook</th><th>Activity</th><th>Submitted</th><th>Status</th><th>Mark</th></tr></thead><tbody>${recent.map(r=>`<tr><td>${esc(r.students?.name)}</td><td>${esc(r.activities?.workbooks?.title)}<div class="small muted">${esc(r.activities?.workbooks?.subject)} · T${r.activities?.workbooks?.term}</div></td><td>${esc(r.activities?.title)}</td><td>${fmtDateTime(r.submitted_at)}</td><td>${statusPill(r.status)}</td><td>${r.score==null?'—':`${esc(r.score)}/${esc(r.activities?.total_marks)}`}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No submissions yet.</div>'}</div>`,'dashboard');
}

function statusPill(s){ const m={submitted:['blue','Submitted'],marked:['green','Marked'],corrections:['amber','Corrections required'],redo:['red','Redo required']}; const [c,l]=m[s]||['','Not submitted']; return `<span class="pill ${c}">${l}</span>`; }

async function pageStudents(){
  const [{data:students,error},{data:workbooks},{data:assignments}] = await Promise.all([
    sb.from('students').select('*').order('grade').order('name'),
    sb.from('workbooks').select('id,title,subject,grade,term,active').order('grade').order('term').order('subject'),
    sb.from('workbook_assignments').select('*')
  ]); if(error) throw error;
  const counts={}; assignments?.forEach(a=>counts[a.student_id]=(counts[a.student_id]||0)+1);
  teacherShell(`<div class="page-head"><div><h1>Students & private links</h1><p>Add learners, assign workbooks and copy their no-login links.</p></div><button id="addStudent" class="btn">＋ Add student</button></div><div class="toolbar"><input id="studentSearch" placeholder="Search students…"><select id="studentGrade"><option value="">All grades</option>${[4,5,6,7,8,9,10,11,12].map(g=>`<option>${g}</option>`).join('')}</select><select id="studentActive"><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Grade</th><th>Code</th><th>Workbooks</th><th>Status</th><th>Private link</th><th>Actions</th></tr></thead><tbody id="studentRows">${students.map(s=>studentRow(s,counts[s.id]||0)).join('')}</tbody></table></div>`,'students');
  const filter=()=>{ const q=$('#studentSearch').value.toLowerCase(),g=$('#studentGrade').value,a=$('#studentActive').value; $$('#studentRows tr').forEach(tr=>tr.classList.toggle('hidden',!( (!q||tr.dataset.name.includes(q)) && (!g||tr.dataset.grade===g) && (!a||tr.dataset.active===a) ))); };
  $('#studentSearch').oninput=filter; $('#studentGrade').onchange=filter; $('#studentActive').onchange=filter;
  $('#addStudent').onclick=()=>studentModal(null,workbooks||[],[]);
  $$('[data-edit-student]').forEach(b=>b.onclick=()=>{const s=students.find(x=>x.id===b.dataset.editStudent);studentModal(s,workbooks||[],assignments.filter(a=>a.student_id===s.id).map(a=>a.workbook_id));});
  $$('[data-copy-link]').forEach(b=>b.onclick=()=>copyStudentLink(students.find(s=>s.id===b.dataset.copyLink)));
  $$('[data-open-link]').forEach(b=>b.onclick=()=>window.open(studentUrl(students.find(s=>s.id===b.dataset.openLink)),'_blank','noopener'));
  $$('[data-rotate-link]').forEach(b=>b.onclick=()=>rotateStudentLink(students.find(s=>s.id===b.dataset.rotateLink),workbooks||[],assignments));
}
function studentRow(s,count){return `<tr data-name="${esc(s.name.toLowerCase())}" data-grade="${s.grade}" data-active="${s.active}"><td><strong>${esc(s.name)}</strong></td><td>Grade ${s.grade}</td><td>${esc(s.student_code||'—')}</td><td>${count}</td><td>${s.active?'<span class="pill green">Active</span>':'<span class="pill">Inactive</span>'}</td><td><button class="btn secondary sm" data-copy-link="${s.id}">Copy link</button> <button class="btn secondary sm" data-open-link="${s.id}">Open</button></td><td><button class="btn secondary sm" data-edit-student="${s.id}">Edit</button> <button class="btn secondary sm" data-rotate-link="${s.id}">New link</button></td></tr>`;}
function studentUrl(s){ const u=new URL(location.origin+location.pathname); u.hash=`${cfg.STUDENT_LINK_PARAM||'s'}=${s.access_token}`; return u.toString(); }
async function copyStudentLink(s){ await navigator.clipboard.writeText(studentUrl(s)); toast(`Private link copied for ${s.name}.`); }
async function rotateStudentLink(s){ if(!confirm(`Replace ${s.name}'s private link? The old link will stop working immediately.`)) return; const {error}=await sb.from('students').update({access_token:token()}).eq('id',s.id); if(error) return toast(error.message,true); toast('New private link created.'); pageStudents(); }
function studentModal(s,workbooks,assigned){
  const active=s?.active!==false;
  modal(`<h2>${s?'Edit student':'Add student'}</h2><form id="studentForm"><div class="form-grid"><div class="field"><label>Student name</label><input name="name" required value="${esc(s?.name||'')}"></div><div class="field"><label>Grade</label><select name="grade" required>${[4,5,6,7,8,9,10,11,12].map(g=>`<option value="${g}" ${Number(s?.grade)===g?'selected':''}>Grade ${g}</option>`).join('')}</select></div><div class="field"><label>Student code (optional)</label><input name="student_code" value="${esc(s?.student_code||'')}"></div><div class="field"><label>Status</label><select name="active"><option value="true" ${active?'selected':''}>Active</option><option value="false" ${!active?'selected':''}>Inactive</option></select></div><div class="field wide"><label>Assign workbooks</label><div class="stack" style="max-height:270px;overflow:auto;border:1px solid var(--line);padding:.7rem;border-radius:10px">${workbooks.filter(w=>w.active).map(w=>`<label><input type="checkbox" name="workbook" value="${w.id}" ${assigned.includes(w.id)?'checked':''}> ${esc(w.subject)} — ${esc(w.title)} · Grade ${w.grade} · Term ${w.term}</label>`).join('')||'<span class="muted">Create a workbook first.</span>'}</div></div></div><div class="modal-actions"><button type="button" class="btn secondary" data-close>Cancel</button><button class="btn">Save student</button></div></form>`);
  $('#studentForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;setBusy(btn,true);const f=new FormData(e.currentTarget);const row={name:f.get('name').trim(),grade:Number(f.get('grade')),student_code:f.get('student_code').trim()||null,active:f.get('active')==='true'};let id=s?.id;if(!s)row.access_token=token();let error;if(s){({error}=await sb.from('students').update(row).eq('id',s.id));}else{const r=await sb.from('students').insert(row).select().single();error=r.error;id=r.data?.id;}if(error){setBusy(btn,false);return toast(error.message,true);}await sb.from('workbook_assignments').delete().eq('student_id',id);const ids=f.getAll('workbook');if(ids.length){const r=await sb.from('workbook_assignments').insert(ids.map(workbook_id=>({student_id:id,workbook_id})));if(r.error){setBusy(btn,false);return toast(r.error.message,true);}}closeModal();toast('Student saved.');pageStudents();};
}

async function pageWorkbooks(){
  const {data:books,error}=await sb.from('workbooks').select('*, activities(count)').order('grade').order('term').order('subject').order('title'); if(error) throw error;
  teacherShell(`<div class="page-head"><div><h1>Workbooks</h1><p>One website can hold every grade, subject and term.</p></div><button id="addWorkbook" class="btn">＋ New workbook</button></div><div class="toolbar"><input id="wbSearch" placeholder="Search workbooks…"><select id="wbGrade"><option value="">All grades</option>${[4,5,6,7,8,9,10,11,12].map(g=>`<option>${g}</option>`).join('')}</select><select id="wbTerm"><option value="">All terms</option>${[1,2,3,4].map(t=>`<option value="${t}">Term ${t}</option>`).join('')}</select></div><div id="wbGrid" class="grid cards">${books.map(w=>`<div class="card workbook-card" data-title="${esc((w.title+' '+w.subject).toLowerCase())}" data-grade="${w.grade}" data-term="${w.term}"><div class="row spread"><span class="pill">Grade ${w.grade}</span><span class="pill blue">Term ${w.term}</span></div><div><div class="small muted">${esc(w.subject)}</div><div class="workbook-title">${esc(w.title)}</div></div><div class="muted small">${esc(w.description||'No description')}</div><div class="row spread"><span>${w.activities?.[0]?.count||0} activities</span>${w.active?'<span class="pill green">Active</span>':'<span class="pill">Inactive</span>'}</div><button class="btn" data-open-wb="${w.id}">Open workbook</button></div>`).join('')||'<div class="empty">No workbooks yet.</div>'}</div>`,'workbooks');
  const filter=()=>{const q=$('#wbSearch').value.toLowerCase(),g=$('#wbGrade').value,t=$('#wbTerm').value;$$('#wbGrid .workbook-card').forEach(c=>c.classList.toggle('hidden',!((!q||c.dataset.title.includes(q))&&(!g||c.dataset.grade===g)&&(!t||c.dataset.term===t))));};$('#wbSearch').oninput=filter;$('#wbGrade').onchange=filter;$('#wbTerm').onchange=filter;
  $('#addWorkbook').onclick=()=>workbookModal(); $$('[data-open-wb]').forEach(b=>b.onclick=()=>location.hash='workbooks:'+b.dataset.openWb);
}
function workbookModal(w){
  modal(`<h2>${w?'Edit workbook':'Create workbook'}</h2><form id="wbForm"><div class="form-grid"><div class="field"><label>Subject</label><input name="subject" required value="${esc(w?.subject||'')}"></div><div class="field"><label>Workbook title</label><input name="title" required value="${esc(w?.title||'')}"></div><div class="field"><label>Grade</label><select name="grade">${[4,5,6,7,8,9,10,11,12].map(g=>`<option value="${g}" ${Number(w?.grade)===g?'selected':''}>Grade ${g}</option>`).join('')}</select></div><div class="field"><label>Term</label><select name="term">${[1,2,3,4].map(t=>`<option value="${t}" ${Number(w?.term||1)===t?'selected':''}>Term ${t}</option>`).join('')}</select></div><div class="field wide"><label>Description</label><textarea name="description">${esc(w?.description||'')}</textarea></div><div class="field"><label>Status</label><select name="active"><option value="true" ${w?.active!==false?'selected':''}>Active</option><option value="false" ${w?.active===false?'selected':''}>Inactive</option></select></div></div><div class="modal-actions"><button type="button" class="btn secondary" data-close>Cancel</button><button class="btn">Save workbook</button></div></form>`);
  $('#wbForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;setBusy(btn,true);const f=new FormData(e.currentTarget);const row={subject:f.get('subject').trim(),title:f.get('title').trim(),grade:Number(f.get('grade')),term:Number(f.get('term')),description:f.get('description').trim()||null,active:f.get('active')==='true',updated_at:new Date().toISOString()};const r=w?await sb.from('workbooks').update(row).eq('id',w.id):await sb.from('workbooks').insert({...row,created_by:currentTeacher.user_id});if(r.error){setBusy(btn,false);return toast(r.error.message,true);}closeModal();toast('Workbook saved.');w?pageWorkbook(w.id):pageWorkbooks();};
}

async function pageWorkbook(id){
  const [{data:w,error},{data:acts},{data:files}] = await Promise.all([sb.from('workbooks').select('*').eq('id',id).single(),sb.from('activities').select('*').eq('workbook_id',id).order('date_loaded').order('created_at'),sb.from('activity_files').select('*').in('activity_id',(await sb.from('activities').select('id').eq('workbook_id',id)).data?.map(x=>x.id)||['00000000-0000-0000-0000-000000000000'])]); if(error) throw error;
  teacherShell(`<div class="page-head"><div><div class="row"><button class="btn secondary sm" id="backWb">← Workbooks</button><span class="pill">Grade ${w.grade}</span><span class="pill blue">Term ${w.term}</span></div><h1 style="margin-top:.6rem">${esc(w.subject)} — ${esc(w.title)}</h1><p>${esc(w.description||'')}</p></div><div class="row"><button id="exportThis" class="btn secondary">Export workbook</button><button id="editWb" class="btn secondary">Edit</button><button id="addActivity" class="btn">＋ Activity</button></div></div><div class="stack">${acts?.map(a=>activityTeacherCard(a,(files||[]).filter(f=>f.activity_id===a.id))).join('')||'<div class="empty">No activities yet. Add the first activity.</div>'}</div>`,'workbooks');
  $('#backWb').onclick=()=>location.hash='workbooks';$('#editWb').onclick=()=>workbookModal(w);$('#addActivity').onclick=()=>activityModal(w,null,[]);$('#exportThis').onclick=e=>exportWorkbookPackage(w.id,e.currentTarget);
  $$('[data-edit-activity]').forEach(b=>{const a=acts.find(x=>x.id===b.dataset.editActivity);activityModal(w,a,(files||[]).filter(f=>f.activity_id===a.id));});
  $$('[data-toggle-memo]').forEach(b=>b.onclick=()=>toggleMemo(b.dataset.toggleMemo,b.dataset.state==='true'));
  $$('[data-delete-activity]').forEach(b=>b.onclick=()=>deleteActivity(b.dataset.deleteActivity,w.id));
  $$('[data-view-file]').forEach(b=>b.onclick=()=>openTeacherFile(b.dataset.viewFile));
}
function activityTeacherCard(a,files){ const qf=files.filter(f=>f.kind==='question'),mf=files.filter(f=>f.kind==='memo');return `<div class="activity ${isOverdue(a.due_date)?'overdue':''}"><div class="row spread"><div><div class="small muted">${esc(a.unit||'Activity')}</div><h3 style="margin:.15rem 0">${esc(a.title)}</h3></div><div class="row">${a.memo_released?'<span class="pill green">Memo released</span>':'<span class="pill">Memo hidden</span>'}${isOverdue(a.due_date)?'<span class="pill red">Due date passed</span>':''}</div></div><div class="row small muted"><span>Loaded: <strong>${fmtDate(a.date_loaded)}</strong></span><span>Due: <strong>${fmtDate(a.due_date)}</strong></span><span>${a.total_marks||0} marks</span><span>${qf.length} question files</span><span>${mf.length} memo files</span></div><p>${nl2br(a.instructions||'')}</p><ol class="question-list">${(a.questions||[]).map(q=>`<li>${esc(q)}</li>`).join('')}</ol>${qf.length?`<div class="row" style="margin-top:.6rem"><span class="small muted">Questions:</span>${qf.map(f=>`<button class="btn secondary sm" data-view-file="${esc(f.storage_path)}">📎 ${esc(f.file_name)}</button>`).join('')}</div>`:''}${mf.length?`<div class="row" style="margin-top:.45rem"><span class="small muted">Memo:</span>${mf.map(f=>`<button class="btn secondary sm" data-view-file="${esc(f.storage_path)}">🔐 ${esc(f.file_name)}</button>`).join('')}</div>`:''}<div class="row" style="margin-top:.8rem"><button class="btn secondary sm" data-edit-activity="${a.id}">Edit</button><button class="btn ${a.memo_released?'amber':'secondary'} sm" data-toggle-memo="${a.id}" data-state="${a.memo_released}">${a.memo_released?'Hide memo':'Reveal memo'}</button><button class="btn danger sm" data-delete-activity="${a.id}">Delete</button></div></div>`; }
async function toggleMemo(id,state){const {error}=await sb.from('activities').update({memo_released:!state,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message,true);toast(!state?'Memo released.':'Memo hidden.');renderTeacherRoute();}
async function deleteActivity(id,wbid){if(!confirm('Delete this activity and all its submissions/files?'))return;const {data:paths}=await sb.from('all_file_paths').select('storage_path').eq('activity_id',id);if(paths?.length)await sb.storage.from(BUCKET).remove(paths.map(x=>x.storage_path));const {error}=await sb.from('activities').delete().eq('id',id);if(error)return toast(error.message,true);toast('Activity deleted.');pageWorkbook(wbid);}
async function openTeacherFile(path){try{window.open(await signed(path),'_blank','noopener');}catch(e){toast(e.message,true);}}
function activityModal(w,a,files){
  const qf=files.filter(f=>f.kind==='question'),mf=files.filter(f=>f.kind==='memo');
  modal(`<h2>${a?'Edit':'Add'} activity — ${esc(w.title)}</h2><form id="activityForm"><div class="form-grid"><div class="field"><label>Unit / section</label><input name="unit" value="${esc(a?.unit||'')}"></div><div class="field"><label>Activity title</label><input name="title" required value="${esc(a?.title||'')}"></div><div class="field"><label>Date loaded</label><input type="date" name="date_loaded" value="${esc(a?.date_loaded||todayISO())}"></div><div class="field"><label>Date due</label><input type="date" name="due_date" value="${esc(a?.due_date||'')}"></div><div class="field"><label>Total marks</label><input type="number" min="0" step="0.5" name="total_marks" value="${esc(a?.total_marks||0)}"></div><div class="field"><label>Memo</label><select name="memo_released"><option value="false" ${!a?.memo_released?'selected':''}>Hidden</option><option value="true" ${a?.memo_released?'selected':''}>Revealed</option></select></div><div class="field wide"><label>Instructions</label><textarea name="instructions">${esc(a?.instructions||'')}</textarea></div><div class="field wide"><label>Questions — one per line</label><textarea name="questions" style="min-height:150px">${esc((a?.questions||[]).join('\n'))}</textarea></div><div class="field wide"><label>Memo / answers — one per line</label><textarea name="memo" style="min-height:150px">${esc((a?.memo||[]).join('\n'))}</textarea></div><div class="field wide"><label>Question images / PDFs</label><input type="file" name="question_files" multiple accept="image/*,application/pdf"><div class="hint">New files are added to existing attachments. Max ${cfg.MAX_FILE_MB||10} MB each.</div>${fileChips(qf)}</div><div class="field wide"><label>Memo images / PDFs</label><input type="file" name="memo_files" multiple accept="image/*,application/pdf"><div class="hint">These stay hidden from learners until the memo is revealed.</div>${fileChips(mf)}</div></div><div class="modal-actions"><button type="button" class="btn secondary" data-close>Cancel</button><button class="btn">Save activity</button></div></form>`);
  $$('[data-open-existing]').forEach(b=>b.onclick=()=>{const f=files.find(x=>x.id===b.dataset.openExisting);if(f)openTeacherFile(f.storage_path);});
  $$('[data-delete-file]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this attachment?'))return;const f=files.find(x=>x.id===b.dataset.deleteFile);await deleteStorage(f.storage_path);await sb.from('activity_files').delete().eq('id',f.id);b.closest('.file-chip').remove();toast('Attachment deleted.');});
  $('#activityForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;setBusy(btn,true,'Saving…');try{const f=new FormData(e.currentTarget);const row={workbook_id:w.id,unit:f.get('unit').trim()||null,title:f.get('title').trim(),instructions:f.get('instructions').trim()||null,total_marks:Number(f.get('total_marks')||0),questions:parseLines(f.get('questions')),memo:parseLines(f.get('memo')),memo_released:f.get('memo_released')==='true',date_loaded:f.get('date_loaded')||null,due_date:f.get('due_date')||null,updated_at:new Date().toISOString()};let aid=a?.id;if(a){const r=await sb.from('activities').update(row).eq('id',a.id);if(r.error)throw r.error;}else{const r=await sb.from('activities').insert({...row,created_by:currentTeacher.user_id}).select().single();if(r.error)throw r.error;aid=r.data.id;}await uploadActivityFiles(aid,[...e.currentTarget.elements.question_files.files],'question');await uploadActivityFiles(aid,[...e.currentTarget.elements.memo_files.files],'memo');closeModal();toast('Activity saved.');pageWorkbook(w.id);}catch(err){setBusy(btn,false);toast(err.message||String(err),true);}};
}
function fileChips(files){return files.length?`<div class="file-list" style="margin-top:.5rem">${files.map(f=>`<div class="file-chip"><span>📎 ${esc(f.file_name)}</span><span class="row"><button type="button" class="btn secondary sm" data-open-existing="${f.id}">Open</button><button type="button" class="btn danger sm" data-delete-file="${f.id}">Delete</button></span></div>`).join('')}</div>`:'';}
async function uploadActivityFiles(aid,files,kind){for(const file of files){const path=`activity-${kind}/${aid}/${uuid()}_${safeFile(file.name)}`;await teacherUpload(file,path);const {error}=await sb.from('activity_files').insert({activity_id:aid,kind,storage_path:path,file_name:file.name,mime_type:file.type||inferMime(file.name)});if(error){await deleteStorage(path);throw error;}}}

async function pageSubmissions(){
  const {data:subs,error}=await sb.from('submissions').select('*,students(id,name,grade),activities(id,title,total_marks,date_loaded,due_date,workbook_id,workbooks(id,title,subject,grade,term))').order('submitted_at',{ascending:false}); if(error) throw error;
  teacherShell(`<div class="page-head"><div><h1>Student submissions</h1><p>Review scripts, build AI marking PDFs, return corrected work and marks.</p></div></div><div class="toolbar"><input id="subSearch" placeholder="Search student/activity…"><select id="subTerm"><option value="">All terms</option>${[1,2,3,4].map(t=>`<option value="${t}">Term ${t}</option>`).join('')}</select><select id="subStatus"><option value="">All statuses</option><option value="submitted">Submitted</option><option value="marked">Marked</option><option value="corrections">Corrections required</option><option value="redo">Redo required</option></select></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Workbook</th><th>Activity</th><th>Submitted</th><th>Status</th><th>Mark</th><th>Actions</th></tr></thead><tbody id="subRows">${subs.map(s=>`<tr data-search="${esc((s.students?.name+' '+s.activities?.title+' '+s.activities?.workbooks?.title+' '+s.activities?.workbooks?.subject).toLowerCase())}" data-term="${s.activities?.workbooks?.term}" data-status="${esc(s.status)}"><td><strong>${esc(s.students?.name)}</strong><div class="small muted">Grade ${s.students?.grade}</div></td><td>${esc(s.activities?.workbooks?.subject)}<div class="small muted">${esc(s.activities?.workbooks?.title)} · T${s.activities?.workbooks?.term}</div></td><td>${esc(s.activities?.title)}</td><td>${fmtDateTime(s.submitted_at)}</td><td>${statusPill(s.status)}</td><td>${s.score==null?'—':`${esc(s.score)}/${esc(s.activities?.total_marks)} (${moneylessPercent(s.score,s.activities?.total_marks)}%)`}</td><td><div class="row"><button class="btn secondary sm" data-review="${s.id}">Review</button><button class="btn sm" data-pack="${s.id}">AI PDF</button></div></td></tr>`).join('')||'<tr><td colspan="7">No submissions yet.</td></tr>'}</tbody></table></div>`,'submissions');
  const filter=()=>{const q=$('#subSearch').value.toLowerCase(),t=$('#subTerm').value,st=$('#subStatus').value;$$('#subRows tr[data-search]').forEach(r=>r.classList.toggle('hidden',!((!q||r.dataset.search.includes(q))&&(!t||r.dataset.term===t)&&(!st||r.dataset.status===st))));};$('#subSearch').oninput=filter;$('#subTerm').onchange=filter;$('#subStatus').onchange=filter;
  $$('[data-review]').forEach(b=>b.onclick=()=>reviewSubmission(subs.find(s=>s.id===b.dataset.review))); $$('[data-pack]').forEach(b=>b.onclick=()=>makeMarkingPack(subs.find(s=>s.id===b.dataset.pack),b));
}
async function reviewSubmission(s){
  const [{data:script},{data:corrected}] = await Promise.all([sb.from('submission_files').select('*').eq('submission_id',s.id).order('page_order'),sb.from('corrected_files').select('*').eq('submission_id',s.id).order('created_at')]);
  modal(`<h2>${esc(s.students.name)} — ${esc(s.activities.title)}</h2><div class="row"><span class="pill">${esc(s.activities.workbooks.subject)}</span><span class="pill blue">Term ${s.activities.workbooks.term}</span><span>${fmtDateTime(s.submitted_at)}</span></div><h3>Student script</h3>${script?.length?`<div class="file-list">${script.map(f=>`<div class="file-chip"><span>📄 ${esc(f.file_name)}</span><button class="btn secondary sm" data-view-script="${esc(f.storage_path)}">Open</button></div>`).join('')}</div>`:'<div class="empty">No files recorded.</div>'}<form id="markForm" style="margin-top:1rem"><div class="form-grid"><div class="field"><label>Score / ${s.activities.total_marks}</label><input type="number" name="score" min="0" max="${s.activities.total_marks||9999}" step="0.5" value="${esc(s.score??'')}"></div><div class="field"><label>Status</label><select name="status"><option value="marked" ${s.status==='marked'?'selected':''}>Marked / complete</option><option value="corrections" ${s.status==='corrections'?'selected':''}>Corrections required</option><option value="redo" ${s.status==='redo'?'selected':''}>Redo activity</option><option value="submitted" ${s.status==='submitted'?'selected':''}>Submitted / awaiting marking</option></select></div><div class="field wide"><label>Teacher comment</label><textarea name="teacher_comment">${esc(s.teacher_comment||'')}</textarea></div><div class="field wide"><label>Upload corrected work</label><input type="file" name="corrected" multiple accept="image/*,application/pdf">${corrected?.length?`<div class="file-list" style="margin-top:.5rem">${corrected.map(f=>`<div class="file-chip"><span>✅ ${esc(f.file_name)}</span><button type="button" class="btn secondary sm" data-view-corrected="${esc(f.storage_path)}">Open</button></div>`).join('')}</div>`:''}</div></div><div class="modal-actions"><button type="button" class="btn secondary" data-close>Close</button><button class="btn">Save marking</button></div></form>`);
  $$('[data-view-script],[data-view-corrected]').forEach(b=>b.onclick=()=>openTeacherFile(b.dataset.viewScript||b.dataset.viewCorrected));
  $('#markForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;setBusy(btn,true,'Saving…');try{const f=new FormData(e.currentTarget);const score=f.get('score')===''?null:Number(f.get('score'));const {error}=await sb.from('submissions').update({score,status:f.get('status'),teacher_comment:f.get('teacher_comment').trim()||null,marked_at:new Date().toISOString(),marked_by:currentTeacher.user_id}).eq('id',s.id);if(error)throw error;for(const file of e.currentTarget.elements.corrected.files){const path=`corrected/${s.students.id}/${s.activities.id}/${uuid()}_${safeFile(file.name)}`;await teacherUpload(file,path);const r=await sb.from('corrected_files').insert({submission_id:s.id,storage_path:path,file_name:file.name,mime_type:file.type||inferMime(file.name)});if(r.error)throw r.error;}closeModal();toast('Marking saved and learner hub updated.');pageSubmissions();}catch(err){setBusy(btn,false);toast(err.message,true);}};
}

async function makeMarkingPack(s,btn){
  setBusy(btn,true,'Building…');
  try{
    const [{data:a},{data:af},{data:sf}] = await Promise.all([sb.from('activities').select('*,workbooks(*)').eq('id',s.activities.id).single(),sb.from('activity_files').select('*').eq('activity_id',s.activities.id).order('sort_order'),sb.from('submission_files').select('*').eq('submission_id',s.id).order('page_order')]);
    const PDF=window.PDFLib; if(!PDF) throw new Error('PDF library did not load.'); const doc=await PDF.PDFDocument.create(); const font=await doc.embedFont(PDF.StandardFonts.Helvetica); const bold=await doc.embedFont(PDF.StandardFonts.HelveticaBold);
    addTextPages(doc,font,bold,`${a.workbooks.subject} — ${a.workbooks.title}\n${a.title}`, [`Student: ${s.students.name}`,`Grade: ${s.students.grade} | Term: ${a.workbooks.term}`,`Loaded: ${fmtDate(a.date_loaded)} | Due: ${fmtDate(a.due_date)}`,`Total marks: ${a.total_marks}`,'','QUESTIONS',...(a.questions||[]).map((q,i)=>`${i+1}. ${q}`),'','OFFICIAL MEMO',...(a.memo||[]).map((m,i)=>`${i+1}. ${m}`)]);
    const append=async(f,label)=>{
      const url=await signed(f.storage_path,900);const res=await fetch(url);const blob=await res.blob();const bytes=new Uint8Array(await blob.arrayBuffer());
      if((f.mime_type||'').includes('pdf')||f.file_name.toLowerCase().endsWith('.pdf')){
        const src=await PDF.PDFDocument.load(bytes);const pages=await doc.copyPages(src,src.getPageIndices());pages.forEach(p=>doc.addPage(p));return;
      }
      if((f.mime_type||'').startsWith('image/')||/\.(png|jpe?g|webp|hei[cf])$/i.test(f.file_name)){
        try{
          let img;const isPng=(f.mime_type||'').includes('png')||/\.png$/i.test(f.file_name);const isJpg=(f.mime_type||'').includes('jpeg')||/\.jpe?g$/i.test(f.file_name);
          if(isPng)img=await doc.embedPng(bytes);else if(isJpg)img=await doc.embedJpg(bytes);else{const bmp=await createImageBitmap(blob);const canvas=document.createElement('canvas');canvas.width=bmp.width;canvas.height=bmp.height;canvas.getContext('2d').drawImage(bmp,0,0);const pngBlob=await new Promise((resolve,reject)=>canvas.toBlob(x=>x?resolve(x):reject(new Error('Image conversion failed.')),'image/png'));img=await doc.embedPng(new Uint8Array(await pngBlob.arrayBuffer()));bmp.close?.();}
          const page=doc.addPage([595,842]);page.drawText(label,{x:36,y:810,size:12,font:bold});const maxW=523,maxH=750,sc=Math.min(maxW/img.width,maxH/img.height);page.drawImage(img,{x:(595-img.width*sc)/2,y:35,width:img.width*sc,height:img.height*sc});return;
        }catch(err){console.warn('Could not embed image',f.file_name,err);addTextPages(doc,font,bold,label,[`Image attachment could not be embedded: ${f.file_name}`]);return;}
      }
      addTextPages(doc,font,bold,label,[`Attachment: ${f.file_name}`]);
    };
    for(const f of (af||[]).filter(x=>x.kind==='question')) await append(f,'Question/source attachment');
    for(const f of (af||[]).filter(x=>x.kind==='memo')) await append(f,'Memo attachment');
    addTextPages(doc,font,bold,'STUDENT SCRIPT',[`Student: ${s.students.name}`,`Submitted: ${fmtDateTime(s.submitted_at)}`]);
    for(const f of sf||[]) await append(f,'Student script');
    const bytes=await doc.save();downloadBlob(new Blob([bytes],{type:'application/pdf'}),`${safeFile(s.students.name)}_${safeFile(a.title)}_AI_Marking_Pack.pdf`);toast('AI marking PDF created.');
  }catch(e){console.error(e);toast(e.message||String(e),true);}finally{setBusy(btn,false);}
}
function addTextPages(doc,font,bold,title,lines){const size=[595,842],margin=42,maxW=511;let page=doc.addPage(size),y=798;page.drawText(title,{x:margin,y,size:16,font:bold,maxWidth:maxW});y-=34;for(const raw of lines){const txt=String(raw??'');const wrapped=wrapText(txt,88);for(const line of wrapped){if(y<55){page=doc.addPage(size);y=798;}page.drawText(line,{x:margin,y,size:10.5,font,lineHeight:14,maxWidth:maxW});y-=14;}y-=txt===''?6:2;}}
function wrapText(t,max){if(!t)return [''];const words=t.split(/\s+/);const out=[];let line='';for(const w of words){if((line+' '+w).trim().length>max){if(line)out.push(line);line=w;}else line=(line+' '+w).trim();}if(line)out.push(line);return out;}

async function pageBackup(){
  teacherShell(`<div class="page-head"><div><h1>Import / Export</h1><p>Move workbooks between systems and keep a complete off-site backup.</p></div></div><div class="grid cards"><div class="card"><h2>Import workbook package</h2><p class="muted">Import a ZIP previously exported by this app, including activity attachments.</p><input id="importWbZip" type="file" accept=".zip"><div class="row" style="margin-top:.7rem"><button id="doImportZip" class="btn">Import workbook ZIP</button><a class="btn secondary" href="templates/sample_workbook_package.zip" download>Sample ZIP</a></div></div><div class="card"><h2>Import workbook CSV</h2><p class="muted">Fast bulk import for text-based workbooks/activities. Attachments can be added afterwards.</p><input id="importCsv" type="file" accept=".csv,text/csv"><div class="row" style="margin-top:.7rem"><button id="doImportCsv" class="btn">Import CSV</button><a class="btn secondary" href="templates/workbook_import_template.csv" download>CSV template</a></div></div><div class="card"><h2>Export everything</h2><p class="muted">Creates a ZIP containing a database backup JSON plus every question, memo, learner submission and corrected file.</p><button id="fullBackup" class="btn">Download full backup ZIP</button><p class="hint">Large systems can produce a large ZIP and may use significant browser memory.</p></div><div class="card"><h2>Export students</h2><p class="muted">Download learner names, grades, codes and private links as CSV.</p><button id="exportStudents" class="btn secondary">Download students CSV</button></div></div>`,'backup');
  $('#doImportZip').onclick=e=>importWorkbookZip($('#importWbZip').files[0],e.currentTarget); $('#doImportCsv').onclick=e=>importWorkbookCsv($('#importCsv').files[0],e.currentTarget); $('#fullBackup').onclick=e=>fullBackup(e.currentTarget); $('#exportStudents').onclick=exportStudentsCsv;
}
async function exportStudentsCsv(){const {data,error}=await sb.from('students').select('*').order('grade').order('name');if(error)return toast(error.message,true);const rows=data.map(s=>({name:s.name,grade:s.grade,student_code:s.student_code||'',active:s.active,private_link:studentUrl(s)}));downloadBlob(new Blob([toCSV(rows,['name','grade','student_code','active','private_link'])],{type:'text/csv'}),'students.csv');}
async function exportWorkbookPackage(id,btn){setBusy(btn,true,'Exporting…');try{const [{data:w,error},{data:acts}] = await Promise.all([sb.from('workbooks').select('*').eq('id',id).single(),sb.from('activities').select('*').eq('workbook_id',id).order('created_at')]);if(error)throw error;const af=(await sb.from('activity_files').select('*').in('activity_id',acts.map(a=>a.id).length?acts.map(a=>a.id):['00000000-0000-0000-0000-000000000000'])).data||[];const zip=new JSZip();const manifest={format:'snt-workbook-package-v1',exported_at:new Date().toISOString(),workbook:{...w,id:undefined,created_by:undefined},activities:[]};for(const a of acts){const item={...a,id:undefined,workbook_id:undefined,created_by:undefined,files:[]};for(const f of af.filter(x=>x.activity_id===a.id)){const rel=`files/${a.id}/${uuid()}_${safeFile(f.file_name)}`;const url=await signed(f.storage_path,1200);zip.file(rel,await (await fetch(url)).blob());item.files.push({kind:f.kind,file_name:f.file_name,mime_type:f.mime_type,zip_path:rel,sort_order:f.sort_order});}manifest.activities.push(item);}zip.file('workbook.json',JSON.stringify(manifest,null,2));downloadBlob(await zip.generateAsync({type:'blob'}),`${safeFile(w.subject)}_${safeFile(w.title)}_workbook.zip`);toast('Workbook package exported.');}catch(e){toast(e.message,true);}finally{setBusy(btn,false);}}
async function importWorkbookZip(file,btn){if(!file)return toast('Choose a workbook ZIP first.',true);setBusy(btn,true,'Importing…');try{const zip=await JSZip.loadAsync(file);const mf=zip.file('workbook.json');if(!mf)throw new Error('workbook.json was not found in this ZIP.');const m=JSON.parse(await mf.async('text'));if(m.format!=='snt-workbook-package-v1')throw new Error('This is not an SNT workbook package.');const {data:w,error}=await sb.from('workbooks').insert({...m.workbook,title:m.workbook.title+' (Imported)',created_by:currentTeacher.user_id,created_at:new Date().toISOString(),updated_at:new Date().toISOString()}).select().single();if(error)throw error;for(const a of m.activities||[]){const files=a.files||[];delete a.files;delete a.created_at;delete a.updated_at;const {data:na,error:ae}=await sb.from('activities').insert({...a,workbook_id:w.id,created_by:currentTeacher.user_id}).select().single();if(ae)throw ae;for(const f of files){const zf=zip.file(f.zip_path);if(!zf)continue;const blob=await zf.async('blob');const path=`activity-${f.kind}/${na.id}/${uuid()}_${safeFile(f.file_name)}`;await teacherUpload(new File([blob],f.file_name,{type:f.mime_type||blob.type}),path);const r=await sb.from('activity_files').insert({activity_id:na.id,kind:f.kind,storage_path:path,file_name:f.file_name,mime_type:f.mime_type||null,sort_order:f.sort_order||0});if(r.error)throw r.error;}}toast('Workbook imported successfully.');pageWorkbooks();}catch(e){toast(e.message||String(e),true);}finally{setBusy(btn,false);}}
async function importWorkbookCsv(file,btn){if(!file)return toast('Choose a CSV first.',true);setBusy(btn,true,'Importing…');try{const rows=parseCSV(await file.text());if(!rows.length)throw new Error('CSV has no data rows.');const grouped=new Map();for(const r of rows){const key=[r.workbook_title,r.subject,r.grade,r.term].join('|');if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(r);}for(const group of grouped.values()){const first=group[0];const {data:w,error}=await sb.from('workbooks').insert({title:first.workbook_title,subject:first.subject,grade:Number(first.grade),term:Number(first.term),description:first.description||null,active:true,created_by:currentTeacher.user_id}).select().single();if(error)throw error;for(const r of group){const ins=await sb.from('activities').insert({workbook_id:w.id,unit:r.unit||null,title:r.activity_title,instructions:r.instructions||null,total_marks:Number(r.total_marks||0),date_loaded:r.date_loaded||todayISO(),due_date:r.due_date||null,questions:(r.questions_pipe||'').split('|').map(x=>x.trim()).filter(Boolean),memo:(r.memo_pipe||'').split('|').map(x=>x.trim()).filter(Boolean),memo_released:String(r.memo_released).toLowerCase()==='true',created_by:currentTeacher.user_id});if(ins.error)throw ins.error;}}toast('CSV workbooks imported.');pageWorkbooks();}catch(e){toast(e.message,true);}finally{setBusy(btn,false);}}
function parseCSV(text){const lines=[];let row=[],field='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){field+='"';i++;}else if(c==='"'){q=!q;}else if(c===','&&!q){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(x=>x!==''))lines.push(row);row=[];field='';}else field+=c;}row.push(field);if(row.some(x=>x!==''))lines.push(row);if(lines.length<2)return[];const h=lines[0].map(x=>x.trim());return lines.slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]||'').trim()])));}
async function fullBackup(btn){setBusy(btn,true,'Building backup…');try{const tables=['teacher_profiles','students','workbooks','workbook_assignments','activities','activity_files','submissions','submission_files','corrected_files'];const backup={format:'snt-full-backup-v1',exported_at:new Date().toISOString(),tables:{}};for(const t of tables){const {data,error}=await sb.from(t).select('*');if(error)throw error;backup.tables[t]=data||[];}const zip=new JSZip();zip.file('backup.json',JSON.stringify(backup,null,2));const paths=[...backup.tables.activity_files,...backup.tables.submission_files,...backup.tables.corrected_files];let i=0;for(const f of paths){i++;btn.textContent=`Files ${i}/${paths.length}`;try{const url=await signed(f.storage_path,1800);zip.file(`storage/${f.storage_path}`,await (await fetch(url)).blob());}catch(e){console.warn('Backup skipped file',f.storage_path,e);}}btn.textContent='Compressing…';downloadBlob(await zip.generateAsync({type:'blob'}),`SNT_Workbook_Hub_Full_Backup_${todayISO()}.zip`);toast('Full backup created.');}catch(e){toast(e.message,true);}finally{setBusy(btn,false);}}

function modal(html){let old=$('.modal-backdrop');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop"><div class="modal">${html}</div></div>`);$$('[data-close]').forEach(b=>b.onclick=closeModal);$('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))closeModal();};}
function closeModal(){ $('.modal-backdrop')?.remove(); }

// ---------- Student portal (no sign-in) ----------
async function studentApi(action,payload={},file=null){
  const url=`${cfg.SUPABASE_URL}/functions/v1/student-api?action=${encodeURIComponent(action)}`;
  const headers={'x-student-token':studentToken,'apikey':cfg.SUPABASE_PUBLISHABLE_KEY}; let body;
  if(file){body=new FormData();body.append('activity_id',payload.activity_id);body.append('file',file);}
  else{headers['Content-Type']='application/json';body=JSON.stringify(payload);}
  const res=await fetch(url,{method:'POST',headers,body}); const text=await res.text(); let data={}; try{data=text?JSON.parse(text):{};}catch{data={error:text};} if(!res.ok)throw new Error(data.error||`Request failed (${res.status})`); return data;
}
async function startStudent(){
  try{studentHubCache=await studentApi('hub');renderStudentHub(studentHubCache);}catch(e){app.innerHTML=`<div class="login"><div class="login-card"><div class="login-logo">SNT</div><h1>Private workbook link</h1><div class="error-box">${esc(e.message)}</div><p class="muted">Ask your teacher for a new workbook link if this one has expired or was replaced.</p></div></div>`;}
}
function renderStudentHub(hub){
  const s=hub.student,books=hub.workbooks||[]; const allActs=books.flatMap(b=>b.activities||[]),done=allActs.filter(a=>a.submission).length,pct=allActs.length?Math.round(done/allActs.length*100):0;
  app.innerHTML=`<div class="student-page"><div class="student-shell"><section class="student-hero"><div class="small">${esc(cfg.APP_NAME||'SNT Workbook Hub')}</div><h1>Welcome, ${esc(s.name)}</h1><div>Grade ${s.grade} · ${done}/${allActs.length} activities submitted</div><div class="progress" style="margin-top:.7rem;background:#ffffff44"><span style="width:${pct}%;background:#fff"></span></div><div class="student-filters"><select id="studentTerm"><option value="">All terms</option>${[1,2,3,4].map(t=>`<option value="${t}">Term ${t}</option>`).join('')}</select><select id="studentSubject"><option value="">All subjects</option>${[...new Set(books.map(b=>b.subject))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}</select></div></section><div id="studentBooks" class="stack">${books.map(studentBookCard).join('')||'<div class="empty">No workbooks have been assigned to you yet.</div>'}</div><p class="small muted" style="text-align:center;margin:1.5rem">Keep this private link safe. It opens your own workbook hub.</p></div></div>`;
  const filter=()=>{const t=$('#studentTerm').value,sub=$('#studentSubject').value;$$('[data-student-book]').forEach(c=>c.classList.toggle('hidden',!((!t||c.dataset.term===t)&&(!sub||c.dataset.subject===sub))));};$('#studentTerm').onchange=filter;$('#studentSubject').onchange=filter;
  $$('[data-open-activity]').forEach(b=>b.onclick=()=>{const book=books.find(x=>x.id===b.dataset.book);const a=book.activities.find(x=>x.id===b.dataset.openActivity);studentActivityModal(book,a);});
}
function studentBookCard(b){const acts=b.activities||[],done=acts.filter(a=>a.submission).length;return `<div class="card" data-student-book data-term="${b.term}" data-subject="${esc(b.subject)}"><div class="row spread"><div><div class="small muted">${esc(b.subject)} · Grade ${b.grade}</div><div class="workbook-title">${esc(b.title)}</div></div><span class="pill blue">Term ${b.term}</span></div><p class="muted">${esc(b.description||'')}</p><div class="progress"><span style="width:${acts.length?Math.round(done/acts.length*100):0}%"></span></div><div class="small muted" style="margin:.35rem 0 .75rem">${done} of ${acts.length} submitted</div><div class="stack">${acts.map(a=>`<div class="activity ${isOverdue(a.due_date)&&!a.submission?'overdue':''}"><div class="row spread"><div><strong>${esc(a.title)}</strong><div class="small muted">${esc(a.unit||'')}</div></div>${a.submission?statusPill(a.submission.status):(isOverdue(a.due_date)?'<span class="pill red">Overdue</span>':'<span class="pill">Not submitted</span>')}</div><div class="small"><span>Loaded ${fmtDate(a.date_loaded)}</span> · <span class="due ${isOverdue(a.due_date)&&!a.submission?'overdue':''}">Due ${fmtDate(a.due_date)}</span></div><button class="btn sm" style="margin-top:.6rem" data-open-activity="${a.id}" data-book="${b.id}">${a.submission?'Open activity':'Do activity'}</button></div>`).join('')||'<div class="muted">No activities yet.</div>'}</div></div>`;}
function studentActivityModal(book,a){
  const sub=a.submission;modal(`<div class="row spread"><div><div class="small muted">${esc(book.subject)} · ${esc(book.title)}</div><h2 style="margin:.15rem 0">${esc(a.title)}</h2></div><button type="button" class="btn secondary sm" data-close>Close</button></div><div class="row small"><span class="pill">Loaded ${fmtDate(a.date_loaded)}</span><span class="pill ${isOverdue(a.due_date)&&!sub?'red':''}">Due ${fmtDate(a.due_date)}</span><span class="pill">${a.total_marks||0} marks</span></div><h3>Instructions</h3><p>${nl2br(a.instructions||'Write the answers in your book and upload your pages below.')}</p><h3>Questions</h3><ol class="question-list">${(a.questions||[]).map(q=>`<li>${esc(q)}</li>`).join('')}</ol>${studentAttachments(a.question_files,'Question attachment')}<hr style="border:0;border-top:1px solid var(--line);margin:1rem 0"><h3>Your work</h3>${sub?`<div class="info-box">${statusPill(sub.status)} Submitted ${fmtDateTime(sub.submitted_at)}${sub.score!=null?` · <strong>${sub.score}/${a.total_marks} (${moneylessPercent(sub.score,a.total_marks)}%)</strong>`:''}</div>${sub.teacher_comment?`<p><strong>Teacher comment:</strong> ${nl2br(sub.teacher_comment)}</p>`:''}${studentAttachments(sub.files,'Your uploaded page')}${studentAttachments(sub.corrected_files,'Corrected work')}`:'<p class="muted">Take clear photos of each page or upload a PDF. Multiple pages are allowed.</p>'}<form id="studentUploadForm"><div class="field"><label>${sub?'Add / resubmit pages':'Upload your pages'}</label><input type="file" name="files" multiple accept="image/*,application/pdf"><div class="hint">Gallery/files: choose multiple images or PDFs.</div><input type="file" name="camera" accept="image/*" capture="environment"><div class="hint">Camera: add one fresh photo. You can submit gallery files and a camera photo together.</div></div><div class="modal-actions"><button class="btn">${sub?'Submit updated work':'Submit work'}</button></div></form>${a.memo_released?`<hr style="border:0;border-top:1px solid var(--line);margin:1rem 0"><h3>✅ Memo released</h3><ol class="question-list">${(a.memo||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol>${studentAttachments(a.memo_files,'Memo attachment')}`:'<div class="info-box">🔒 The memo is hidden until your teacher releases it.</div>'}`);
  $('#studentUploadForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;const files=[...e.currentTarget.elements.files.files,...e.currentTarget.elements.camera.files];if(!files.length)return toast('Choose at least one image or PDF.',true);setBusy(btn,true,'Uploading…');try{for(let i=0;i<files.length;i++){btn.textContent=`Uploading ${i+1}/${files.length}`;await studentApi('upload',{activity_id:a.id},files[i]);}await studentApi('submit',{activity_id:a.id});studentHubCache=await studentApi('hub');closeModal();renderStudentHub(studentHubCache);toast('Work submitted successfully.');}catch(err){setBusy(btn,false);toast(err.message,true);}};
}
function studentAttachments(files,label){if(!files?.length)return'';return `<div class="attachment-grid" style="margin-top:.7rem">${files.map(f=>`<div class="attachment">${f.mime_type?.startsWith('image/')?`<img src="${esc(f.url)}" alt="${esc(label)}">`:''}<a href="${esc(f.url)}" target="_blank" rel="noopener">📎 ${esc(f.file_name)}</a></div>`).join('')}</div>`;}

async function teacherLinkLogin(){
  const {data:{session}}=await sb.auth.getSession();
  if(session){ const u=new URL(location.href);u.searchParams.delete(cfg.TEACHER_LINK_PARAM||'teacher');if(u.hash.startsWith('#teacher='))u.hash='';history.replaceState({},'',u.pathname+u.search+u.hash);return startTeacher(); }
  try{
    const res=await fetch(`${cfg.SUPABASE_URL}/functions/v1/teacher-link`,{method:'POST',headers:{'x-teacher-token':teacherLinkToken,'apikey':cfg.SUPABASE_PUBLISHABLE_KEY}});
    const data=await res.json();if(!res.ok)throw new Error(data.error||'Teacher link failed.');
    location.replace(data.action_link);
  }catch(e){app.innerHTML=`<div class="login"><div class="login-card"><div class="login-logo">SNT</div><h1>Teacher link</h1><div class="error-box">${esc(e.message)}</div></div></div>`;}
}
async function boot(){ if(!configured)return setupScreen(); if(studentToken)return startStudent(); if(teacherLinkToken)return teacherLinkLogin(); return startTeacher(); }
boot();
