import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const cfg = window.SNT_CONFIG || {};
const app = document.getElementById('app');
const toastEl = document.getElementById('toast');
const studentToken = new URLSearchParams(location.search).get(cfg.STUDENT_LINK_PARAM || 's') || (location.hash.startsWith('#s=') ? new URLSearchParams(location.hash.slice(1)).get(cfg.STUDENT_LINK_PARAM || 's') : null);
const teacherLinkToken = new URLSearchParams(location.search).get(cfg.TEACHER_LINK_PARAM || 'teacher') || (location.hash.startsWith('#teacher=') ? new URLSearchParams(location.hash.slice(1)).get(cfg.TEACHER_LINK_PARAM || 'teacher') : null);
const configured = cfg.SUPABASE_URL && !cfg.SUPABASE_URL.includes('YOUR_PROJECT') && cfg.SUPABASE_PUBLISHABLE_KEY && !cfg.SUPABASE_PUBLISHABLE_KEY.includes('YOUR_');
const sb = configured ? createClient(cfg.SUPABASE_URL, cfg.SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: true, autoRefreshToken: true } }) : null;
const BUCKET = 'workbook-files';
let currentTeacher = null;
let studentHubCache = null;

const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const esc = (v='') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const nl2br = (v='') => esc(v).replace(/\n/g,'<br>');
function linkify(v=''){
  const text=String(v??'');
  const re=/https?:\/\/[^\s<>"']+/gi;
  let out='',last=0,match;
  while((match=re.exec(text))){
    out+=esc(text.slice(last,match.index));
    let url=match[0],trail='';
    while(url && /[.,;:!?)]$/.test(url)){trail=url.slice(-1)+trail;url=url.slice(0,-1);}
    const safe=esc(url);
    out+=`<a class="content-link" href="${safe}" target="_blank" rel="noopener noreferrer">${safe}</a>${esc(trail)}`;
    last=match.index+match[0].length;
  }
  return out+esc(text.slice(last));
}
const linkifyNl2br = (v='') => linkify(v).replace(/\n/g,'<br>');
const fmtDate = v => v ? new Date(v + (String(v).length===10 ? 'T00:00:00' : '')).toLocaleDateString('en-ZA',{day:'2-digit',month:'short',year:'numeric'}) : '—';
const fmtDateTime = v => v ? new Date(v).toLocaleString('en-ZA',{dateStyle:'medium',timeStyle:'short'}) : '—';
const todayISO = () => new Date().toISOString().slice(0,10);
const isOverdue = d => !!d && d < todayISO();
const safeFile = n => n.replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-100);
const inferMime = (name='') => /\.pdf$/i.test(name)?'application/pdf':/\.png$/i.test(name)?'image/png':/\.webp$/i.test(name)?'image/webp':/\.hei[cf]$/i.test(name)?'image/heic':/\.jpe?g$/i.test(name)?'image/jpeg':'application/octet-stream';
const uuid = () => crypto.randomUUID();
const token = () => { const b = new Uint8Array(32); crypto.getRandomValues(b); return btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); };
async function sha256Hex(value){ const bytes=new TextEncoder().encode(value); const digest=await crypto.subtle.digest('SHA-256',bytes); return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join(''); }
const moneylessPercent = (a,b) => b ? Math.round((Number(a||0)/Number(b))*100) : 0;

function toast(msg, error=false){ toastEl.textContent=msg; toastEl.className='toast show'+(error?' error':''); clearTimeout(toastEl._t); toastEl._t=setTimeout(()=>toastEl.className='toast',3300); }
function downloadBlob(blob,name){ const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1500); }
function csvEscape(v){ const s=String(v??''); return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s; }
function toCSV(rows,cols){ return [cols.join(','),...rows.map(r=>cols.map(c=>csvEscape(r[c])).join(','))].join('\n'); }
function parseLines(v){ return String(v||'').split('\n').map(x=>x.trim()).filter(Boolean); }
function normalizeExternalUrl(raw){
  let u;try{u=new URL(String(raw||'').trim());}catch{throw new Error(`Invalid web link: ${raw}`);}
  if(!['http:','https:'].includes(u.protocol))throw new Error('Web attachments must use http:// or https:// links.');
  return u.toString();
}
function externalLinkLabel(url){
  const u=new URL(url),host=u.hostname.replace(/^www\./,'').toLowerCase(),path=u.pathname.toLowerCase();
  if(host==='docs.google.com'){
    if(path.includes('/document/'))return 'Google Doc';
    if(path.includes('/spreadsheets/'))return 'Google Sheet';
    if(path.includes('/presentation/'))return 'Google Slides';
    if(path.includes('/forms/'))return 'Google Form';
    return 'Google file';
  }
  if(host==='drive.google.com')return 'Google Drive file';
  return u.hostname.replace(/^www\./,'');
}
function parseWebAttachments(v){
  return String(v||'').split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{
    let label='',raw=line;const pipe=line.indexOf('|');
    if(pipe>0){const maybeUrl=line.slice(pipe+1).trim();if(/^https?:\/\//i.test(maybeUrl)){label=line.slice(0,pipe).trim();raw=maybeUrl;}}
    const url=normalizeExternalUrl(raw);return {url,label:label||externalLinkLabel(url)};
  });
}
function setBusy(btn,busy,label='Working…'){ if(!btn)return; if(busy){btn.dataset.old=btn.textContent;btn.textContent=label;btn.disabled=true}else{btn.textContent=btn.dataset.old||btn.textContent;btn.disabled=false} }
async function signed(path, expires=1800){ const {data,error}=await sb.storage.from(BUCKET).createSignedUrl(path,expires); if(error) throw error; return data.signedUrl; }
async function teacherUpload(file,path){ if(file.size > (cfg.MAX_FILE_MB||10)*1024*1024) throw new Error(`${file.name} is larger than ${cfg.MAX_FILE_MB||10} MB.`); const {error}=await sb.storage.from(BUCKET).upload(path,file,{contentType:file.type||inferMime(file.name),upsert:false}); if(error) throw error; }
async function deleteStorage(path){ if(!path) return; await sb.storage.from(BUCKET).remove([path]); }

function setupScreen(){
  app.innerHTML=`<div class="login"><div class="login-card"><div class="login-logo">SNT</div><h1>Workbook Hub setup</h1><p class="muted">Connect this GitHub site to Supabase first.</p><div class="info-box">Open <span class="code">config.js</span> and enter your Supabase Project URL and Publishable/anon key. Then run <span class="code">supabase/setup.sql</span> and deploy the included student Edge Function.</div><p class="small muted">Full instructions are in README.md.</p></div></div>`;
}

function renderLogin(message=''){
  app.innerHTML=`<div class="login"><form id="loginForm" class="login-card"><div class="login-logo">SNT</div><h1>Teacher workspace</h1><p class="muted">All approved teachers share this workspace.</p>${message?`<div class="error-box">${esc(message)}</div>`:''}<div class="field"><label>Email</label><input name="email" type="email" required autocomplete="username"></div><div class="field"><label>Password</label><input name="password" type="password" required autocomplete="current-password"></div><button class="btn" style="width:100%;margin-top:1rem">Sign in</button><p class="small muted">Learners do not sign in. They use their private workbook link.</p></form></div>`;
  $('#loginForm').onsubmit=async e=>{ e.preventDefault(); const b=e.submitter; setBusy(b,true,'Signing in…'); const f=new FormData(e.currentTarget); const {error}=await sb.auth.signInWithPassword({email:f.get('email'),password:f.get('password')}); if(error){renderLogin(error.message);return;} await startTeacher(); };
}

async function startTeacher(){
  const {data:{session}}=await sb.auth.getSession();
  if(!session){renderLogin();return;}
  const {data,error}=await sb.from('teacher_profiles').select('*').eq('user_id',session.user.id).eq('active',true).maybeSingle();
  if(error || !data){ await sb.auth.signOut(); renderLogin('This account is not an approved active teacher.'); return; }
  currentTeacher={...data,email:session.user.email};
  window.addEventListener('hashchange',renderTeacherRoute);
  await renderTeacherRoute();
}

function teacherShell(body,active='dashboard'){
  const nav=[['dashboard','🏠 Dashboard'],['students','👨‍🎓 Students & links'],['workbooks','📚 Workbooks'],['outstanding','⏳ Outstanding work'],['submissions','📤 Submissions'],['backup','💾 Import / Export']];
  app.innerHTML=`<header class="topbar"><div class="brand"><div class="brand-badge">SNT</div><div>${esc(cfg.APP_NAME||'SNT Workbook Hub')}</div></div><div class="top-actions"><span class="small">${esc(currentTeacher.display_name||currentTeacher.email)}</span><button id="signOut" class="btn ghost sm">Sign out</button></div></header><div class="shell"><aside class="sidebar">${nav.map(([k,l])=>`<button class="navbtn ${active===k?'active':''}" data-nav="${k}">${l}</button>`).join('')}</aside><main class="content">${body}</main></div>`;
  $$('[data-nav]').forEach(b=>b.onclick=()=>location.hash=b.dataset.nav);
  $('#signOut').onclick=async()=>{await sb.auth.signOut();location.hash='';renderLogin();};
}

async function renderTeacherRoute(){
  const raw=location.hash.replace(/^#/,'')||'dashboard';
  const [route,id]=raw.split(':');
  try{
    if(route==='students') return pageStudents();
    if(route==='workbooks') return id?pageWorkbook(id):pageWorkbooks();
    if(route==='outstanding') return pageOutstanding();
    if(route==='submissions') return pageSubmissions();
    if(route==='backup') return pageBackup();
    return pageDashboard();
  }catch(e){ console.error(e); teacherShell(`<div class="error-box">${esc(e.message||String(e))}</div>`,'dashboard'); }
}

async function pageDashboard(){
  const [{count:students},{count:workbooks},{count:activities},{count:submissions},{data:recent},{data:linkRows}] = await Promise.all([
    sb.from('students').select('*',{count:'exact',head:true}).eq('active',true),
    sb.from('workbooks').select('*',{count:'exact',head:true}).eq('active',true).eq('archived',false).is('custom_student_id',null),
    sb.from('activities').select('*',{count:'exact',head:true}),
    sb.from('submissions').select('*',{count:'exact',head:true}),
    sb.from('submissions').select('id,submitted_at,status,score,students(name),activities(title,total_marks,workbooks(title,subject,term))').order('submitted_at',{ascending:false}).limit(8),
    sb.from('teacher_access_links').select('id,active,created_at,last_used_at').eq('user_id',currentTeacher.user_id).eq('active',true).order('created_at',{ascending:false}).limit(1)
  ]);
  const hasPrivateLink=!!linkRows?.length;
  teacherShell(`<div class="page-head"><div><h1>Shared teacher workspace</h1><p>Every approved teacher sees and manages the same workbook system.</p></div></div><div class="grid cards"><div class="card"><div class="muted">Active students</div><div class="stat">${students||0}</div></div><div class="card"><div class="muted">Active workbooks</div><div class="stat">${workbooks||0}</div></div><div class="card"><div class="muted">Activities</div><div class="stat">${activities||0}</div></div><div class="card"><div class="muted">Submissions</div><div class="stat">${submissions||0}</div></div></div><div class="card" style="margin-top:1rem"><div class="row spread"><div><h2 style="margin-bottom:.25rem">🔐 Private teacher link</h2><p class="muted" style="margin:0">Create a no-password link for this teacher account. You can save it in a safe place or share it only with trusted teachers. Everyone still sees the same shared workspace.</p></div><button id="createTeacherLink" class="btn">${hasPrivateLink?'Replace private link':'Create private link'}</button></div>${hasPrivateLink?`<div class="small muted" style="margin-top:.6rem">A private link is active. For security the secret itself is never stored, so use <strong>Replace private link</strong> if you need a fresh copy.</div>`:''}</div><div class="card" style="margin-top:1rem"><h2>Recent submissions</h2>${recent?.length?`<div class="table-wrap"><table><thead><tr><th>Student</th><th>Workbook</th><th>Activity</th><th>Submitted</th><th>Status</th><th>Mark</th></tr></thead><tbody>${recent.map(r=>`<tr><td>${esc(r.students?.name)}</td><td>${esc(r.activities?.workbooks?.title)}<div class="small muted">${esc(r.activities?.workbooks?.subject)} · T${r.activities?.workbooks?.term}</div></td><td>${esc(r.activities?.title)}</td><td>${fmtDateTime(r.submitted_at)}</td><td>${statusPill(r.status)}</td><td>${r.score==null?'—':`${esc(r.score)}/${esc(r.activities?.total_marks)}`}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No submissions yet.</div>'}</div>`,'dashboard');
  $('#createTeacherLink').onclick=createTeacherAccessLink;
}

async function createTeacherAccessLink(){
  if(!confirm('Create a new private teacher link? Any older private link for this teacher account will stop working.')) return;
  const raw=token();
  const tokenHash=await sha256Hex(raw);
  const {error:offErr}=await sb.from('teacher_access_links').update({active:false}).eq('user_id',currentTeacher.user_id).eq('active',true);
  if(offErr)return toast(offErr.message,true);
  const {error}=await sb.from('teacher_access_links').insert({user_id:currentTeacher.user_id,token_hash:tokenHash,label:'Private teacher link'});
  if(error)return toast(error.message,true);
  const u=new URL(location.origin+location.pathname);u.hash=`${cfg.TEACHER_LINK_PARAM||'teacher'}=${raw}`;
  const link=u.toString();
  try{await navigator.clipboard.writeText(link);}catch{}
  modal(`<h2>Private teacher link created</h2><div class="info-box"><strong>Save this link now.</strong> For security, the secret part cannot be shown again later.</div><div class="field"><label>Teacher link</label><textarea id="teacherLinkOut" readonly style="min-height:105px">${esc(link)}</textarea></div><p class="small muted">Anyone who has this link can enter this teacher account without typing a password. Keep it somewhere private. Creating another link replaces this one.</p><div class="modal-actions"><button type="button" class="btn secondary" data-close>Close</button><button type="button" class="btn" id="copyTeacherLinkNow">Copy link</button></div>`);
  $('#copyTeacherLinkNow').onclick=async()=>{try{await navigator.clipboard.writeText(link);toast('Teacher link copied.');}catch{ $('#teacherLinkOut').select(); document.execCommand('copy'); toast('Teacher link copied.'); }};
}

function statusPill(s){ const m={submitted:['blue','Submitted'],marked:['green','Marked'],corrections:['amber','Corrections required'],redo:['red','Redo required']}; const [c,l]=m[s]||['','Not submitted']; return `<span class="pill ${c}">${l}</span>`; }

async function pageStudents(){
  const [{data:students,error},{data:workbooks},{data:assignments}] = await Promise.all([
    sb.from('students').select('*').order('grade').order('name'),
    sb.from('workbooks').select('id,title,subject,grade,term,active,archived,source_workbook_id,custom_student_id').order('grade').order('term').order('subject'),
    sb.from('workbook_assignments').select('*')
  ]); if(error) throw error;
  const allBooks=workbooks||[], masters=allBooks.filter(w=>!w.custom_student_id);
  const counts={}; (assignments||[]).forEach(a=>counts[a.student_id]=(counts[a.student_id]||0)+1);
  teacherShell(`<div class="page-head"><div><h1>Students & private links</h1><p>Add learners, assign shared workbooks, or make a private customised copy for one learner only.</p></div><button id="addStudent" class="btn">＋ Add student</button></div><div class="toolbar"><input id="studentSearch" placeholder="Search students…"><select id="studentGrade"><option value="">All grades</option>${[4,5,6,7,8,9,10,11,12].map(g=>`<option>${g}</option>`).join('')}</select><select id="studentActive"><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Grade</th><th>Code</th><th>Workbooks</th><th>Status</th><th>Private link</th><th>Actions</th></tr></thead><tbody id="studentRows">${students.map(x=>studentRow(x,counts[x.id]||0)).join('')}</tbody></table></div>`,'students');
  const filter=()=>{ const q=$('#studentSearch').value.toLowerCase(),g=$('#studentGrade').value,a=$('#studentActive').value; $$('#studentRows tr').forEach(tr=>tr.classList.toggle('hidden',!( (!q||tr.dataset.name.includes(q)) && (!g||tr.dataset.grade===g) && (!a||tr.dataset.active===a) ))); };
  $('#studentSearch').oninput=filter; $('#studentGrade').onchange=filter; $('#studentActive').onchange=filter;
  $('#addStudent').onclick=()=>studentModal(null,masters,[]);
  $$('[data-edit-student]').forEach(b=>b.onclick=()=>{const st=students.find(x=>x.id===b.dataset.editStudent);studentModal(st,masters,(assignments||[]).filter(a=>a.student_id===st.id));});
  $$('[data-manage-student-books]').forEach(b=>b.onclick=()=>{const st=students.find(x=>x.id===b.dataset.manageStudentBooks);studentWorkbooksModal(st,masters,(assignments||[]).filter(a=>a.student_id===st.id),allBooks);});
  $$('[data-copy-link]').forEach(b=>b.onclick=()=>copyStudentLink(students.find(x=>x.id===b.dataset.copyLink)));
  $$('[data-open-link]').forEach(b=>b.onclick=()=>window.open(studentUrl(students.find(x=>x.id===b.dataset.openLink)),'_blank','noopener'));
  $$('[data-rotate-link]').forEach(b=>b.onclick=()=>rotateStudentLink(students.find(x=>x.id===b.dataset.rotateLink)));
}
function studentRow(s,count){return `<tr data-name="${esc(s.name.toLowerCase())}" data-grade="${s.grade}" data-active="${s.active}"><td><strong>${esc(s.name)}</strong></td><td>Grade ${s.grade}</td><td>${esc(s.student_code||'—')}</td><td>${count}</td><td>${s.active?'<span class="pill green">Active</span>':'<span class="pill">Inactive</span>'}</td><td><button class="btn secondary sm" data-copy-link="${s.id}">Copy link</button> <button class="btn secondary sm" data-open-link="${s.id}">Open</button></td><td><div class="row"><button class="btn sm" data-manage-student-books="${s.id}">Workbooks</button><button class="btn secondary sm" data-edit-student="${s.id}">Edit</button><button class="btn secondary sm" data-rotate-link="${s.id}">New link</button></div></td></tr>`;}
function studentUrl(s){ const u=new URL(location.origin+location.pathname); u.hash=`${cfg.STUDENT_LINK_PARAM||'s'}=${s.access_token}`; return u.toString(); }
async function copyStudentLink(s){ await navigator.clipboard.writeText(studentUrl(s)); toast(`Private link copied for ${s.name}.`); }
async function rotateStudentLink(s){ if(!confirm(`Replace ${s.name}'s private link? The old link will stop working immediately.`)) return; const {error}=await sb.from('students').update({access_token:token()}).eq('id',s.id); if(error) return toast(error.message,true); toast('New private link created.'); pageStudents(); }
function studentModal(s,workbooks,currentAssignments){
  const active=s?.active!==false;
  const bookById=new Map((workbooks||[]).map(w=>[w.id,w]));
  const selected=new Set((currentAssignments||[]).map(a=>a.workbook_id));
  const assignable=(workbooks||[]).filter(w=>w.active!==false&&!w.archived&&!w.custom_student_id);
  const subjects=[...new Set(assignable.map(w=>w.subject))].sort((a,b)=>a.localeCompare(b));
  modal(`<h2>${s?'Edit student':'Add student'}</h2><form id="studentForm"><div class="form-grid"><div class="field"><label>Student name</label><input name="name" required value="${esc(s?.name||'')}"></div><div class="field"><label>Grade</label><select name="grade" required>${[4,5,6,7,8,9,10,11,12].map(g=>`<option value="${g}" ${Number(s?.grade)===g?'selected':''}>Grade ${g}</option>`).join('')}</select></div><div class="field"><label>Student code (optional)</label><input name="student_code" value="${esc(s?.student_code||'')}"></div><div class="field"><label>Status</label><select name="active"><option value="true" ${active?'selected':''}>Active</option><option value="false" ${!active?'selected':''}>Inactive</option></select></div><div class="field wide"><label>Assign workbooks</label><div class="allocation-box"><div class="allocation-filters"><select id="allocGrade"><option value="">All grades</option>${[4,5,6,7,8,9,10,11,12].map(g=>`<option value="${g}" ${Number(s?.grade||4)===g?'selected':''}>Grade ${g}</option>`).join('')}</select><select id="allocSubject"><option value="">All subjects</option>${subjects.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select><select id="allocTerm"><option value="">All terms</option>${[1,2,3,4].map(t=>`<option value="${t}">Term ${t}</option>`).join('')}</select><select id="allocWorkbook"><option value="">Choose workbook…</option></select><button type="button" class="btn" id="addWorkbookChoice">＋ Add</button></div><div id="assignedWorkbookList" class="assigned-workbooks"></div></div><div class="hint">Archived workbooks are hidden from new allocations. Any archived workbook already assigned to this learner stays assigned unless you remove it below. Personalized copies are also preserved.</div></div></div><div class="modal-actions"><button type="button" class="btn secondary" data-close>Cancel</button><button class="btn">Save student</button></div></form>`);
  const renderAssigned=()=>{
    const books=[...selected].map(id=>bookById.get(id)).filter(Boolean).sort((a,b)=>a.grade-b.grade||a.term-b.term||a.subject.localeCompare(b.subject)||a.title.localeCompare(b.title));
    $('#assignedWorkbookList').innerHTML=books.length?books.map(w=>`<div class="assigned-workbook-row"><div><strong>${esc(w.title)}</strong><div class="small muted">${esc(w.subject)} · Grade ${w.grade} · Term ${w.term}${w.archived?' · Archived':''}${w.active===false?' · Inactive':''}</div></div><button type="button" class="btn secondary sm" data-remove-assigned="${w.id}">Remove</button></div>`).join(''):'<div class="small muted">No workbooks assigned yet.</div>';
    $$('[data-remove-assigned]').forEach(b=>b.onclick=()=>{selected.delete(b.dataset.removeAssigned);renderAssigned();refreshChoices();});
  };
  const refreshChoices=()=>{
    const g=$('#allocGrade').value,sub=$('#allocSubject').value,t=$('#allocTerm').value;
    const choices=assignable.filter(w=>(!g||String(w.grade)===g)&&(!sub||w.subject===sub)&&(!t||String(w.term)===t)&&!selected.has(w.id));
    $('#allocWorkbook').innerHTML=`<option value="">${choices.length?'Choose workbook…':'No matching workbooks'}</option>${choices.map(w=>`<option value="${w.id}">${esc(w.title)} — ${esc(w.subject)} · G${w.grade} T${w.term}</option>`).join('')}`;
  };
  ['allocGrade','allocSubject','allocTerm'].forEach(id=>$(`#${id}`).onchange=refreshChoices);
  $('#addWorkbookChoice').onclick=()=>{const id=$('#allocWorkbook').value;if(!id)return toast('Choose a workbook first.',true);selected.add(id);renderAssigned();refreshChoices();};
  $('#studentForm [name="grade"]').onchange=e=>{if(!s){$('#allocGrade').value=e.target.value;refreshChoices();}};
  renderAssigned();refreshChoices();
  $('#studentForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;setBusy(btn,true);const f=new FormData(e.currentTarget);const row={name:f.get('name').trim(),grade:Number(f.get('grade')),student_code:f.get('student_code').trim()||null,active:f.get('active')==='true'};let id=s?.id;if(!s)row.access_token=token();try{if(s){const r=await sb.from('students').update(row).eq('id',s.id);if(r.error)throw r.error;}else{const r=await sb.from('students').insert(row).select().single();if(r.error)throw r.error;id=r.data.id;}const existing=currentAssignments||[];const remove=existing.filter(a=>!selected.has(a.workbook_id)).map(a=>a.id);if(remove.length){const r=await sb.from('workbook_assignments').delete().in('id',remove);if(r.error)throw r.error;}const existingMasterIds=new Set(existing.map(a=>a.workbook_id));const add=[...selected].filter(wid=>!existingMasterIds.has(wid));if(add.length){const r=await sb.from('workbook_assignments').insert(add.map(workbook_id=>({student_id:id,workbook_id,assigned_by:currentTeacher.user_id})));if(r.error)throw r.error;}closeModal();toast('Student saved.');pageStudents();}catch(err){setBusy(btn,false);toast(err.message||String(err),true);}};
}
function studentWorkbooksModal(s,masters,assignments,allBooks){
  const assigned=(assignments||[]).map(a=>({assignment:a,master:masters.find(w=>w.id===a.workbook_id),custom:allBooks.find(w=>w.id===a.custom_workbook_id)})).filter(x=>x.master);
  modal(`<h2>${esc(s.name)} — assigned workbooks</h2><div class="row spread"><div class="info-box" style="flex:1"><strong>Student-only editing:</strong> choose <em>Customize for ${esc(s.name)}</em>. The app makes a separate copy. The master workbook and every other student's copy remain unchanged.</div><button class="btn" id="assignAnotherWorkbook">＋ Assign workbook</button></div><div class="stack" style="margin-top:1rem">${assigned.map(x=>`<div class="activity"><div class="row spread"><div><div class="small muted">${esc(x.master.subject)} · Grade ${x.master.grade} · Term ${x.master.term}${x.master.archived?' · Archived':''}</div><strong>${esc(x.master.title)}</strong></div>${x.custom?'<span class="pill green">Personalized</span>':'<span class="pill blue">Shared master</span>'}</div><div class="row" style="margin-top:.7rem"><button class="btn secondary sm" data-open-master="${x.master.id}">Open master</button><button class="btn sm" data-customize-assignment="${x.assignment.id}">${x.custom?'Edit personalized copy':`Customize for ${esc(s.name)}`}</button></div></div>`).join('')||'<div class="empty">No workbooks assigned yet.</div>'}</div><div class="modal-actions"><button type="button" class="btn secondary" data-close>Close</button></div>`);
  $('#assignAnotherWorkbook').onclick=()=>assignWorkbookModal(s,masters,assignments,allBooks);
  $$('[data-open-master]').forEach(b=>b.onclick=()=>{closeModal();location.hash='workbooks:'+b.dataset.openMaster;});
  $$('[data-customize-assignment]').forEach(b=>{const x=assigned.find(z=>z.assignment.id===b.dataset.customizeAssignment);b.onclick=()=>customizeWorkbookForStudent(s,x.assignment,x.master,x.custom,b);});
}
function assignWorkbookModal(student,masters,assignments,allBooks){
  const already=new Set((assignments||[]).map(a=>a.workbook_id));
  const choices=(masters||[]).filter(w=>w.active!==false&&!w.archived&&!already.has(w.id));
  const subjects=[...new Set(choices.map(w=>w.subject))].sort((a,b)=>a.localeCompare(b));
  modal(`<h2>Assign workbook — ${esc(student.name)}</h2><div class="field"><label>Grade</label><select id="quickAssignGrade"><option value="">All grades</option>${[4,5,6,7,8,9,10,11,12].map(g=>`<option value="${g}" ${Number(student.grade)===g?'selected':''}>Grade ${g}</option>`).join('')}</select></div><div class="field" style="margin-top:.7rem"><label>Subject</label><select id="quickAssignSubject"><option value="">All subjects</option>${subjects.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select></div><div class="field" style="margin-top:.7rem"><label>Term</label><select id="quickAssignTerm"><option value="">All terms</option>${[1,2,3,4].map(t=>`<option value="${t}">Term ${t}</option>`).join('')}</select></div><div class="field" style="margin-top:.7rem"><label>Workbook</label><select id="quickAssignWorkbook"></select></div><div class="hint">Archived and inactive workbooks are intentionally hidden here.</div><div class="modal-actions"><button type="button" class="btn secondary" data-close>Cancel</button><button type="button" class="btn" id="saveQuickAssignment">Assign workbook</button></div>`);
  const refresh=()=>{const g=$('#quickAssignGrade').value,sub=$('#quickAssignSubject').value,t=$('#quickAssignTerm').value;const list=choices.filter(w=>(!g||String(w.grade)===g)&&(!sub||w.subject===sub)&&(!t||String(w.term)===t));$('#quickAssignWorkbook').innerHTML=`<option value="">${list.length?'Choose workbook…':'No matching workbooks'}</option>${list.map(w=>`<option value="${w.id}">${esc(w.title)} — ${esc(w.subject)} · G${w.grade} T${w.term}</option>`).join('')}`;};
  ['quickAssignGrade','quickAssignSubject','quickAssignTerm'].forEach(id=>$(`#${id}`).onchange=refresh);refresh();
  $('#saveQuickAssignment').onclick=async e=>{const wid=$('#quickAssignWorkbook').value;if(!wid)return toast('Choose a workbook first.',true);setBusy(e.currentTarget,true,'Assigning…');const {error}=await sb.from('workbook_assignments').insert({student_id:student.id,workbook_id:wid,assigned_by:currentTeacher.user_id});if(error){setBusy(e.currentTarget,false);return toast(error.message,true);}closeModal();toast('Workbook assigned.');pageStudents();};
}
async function customizeWorkbookForStudent(student,assignment,master,existingCustom,btn){
  if(existingCustom){closeModal();location.hash='workbooks:'+existingCustom.id;return;}
  if(!confirm(`Create a private editable copy of “${master.title}” for ${student.name}? Changes to that copy will affect only this student.`))return;
  setBusy(btn,true,'Creating copy…');let newBook=null;const copiedPaths=[];
  try{
    const prior=await sb.from('workbooks').select('*').eq('source_workbook_id',master.id).eq('custom_student_id',student.id).maybeSingle();
    if(prior.error)throw prior.error;
    if(prior.data){const ar=await sb.from('workbook_assignments').update({custom_workbook_id:prior.data.id}).eq('id',assignment.id);if(ar.error)throw ar.error;closeModal();location.hash='workbooks:'+prior.data.id;return;}
    const wr=await sb.from('workbooks').insert({title:master.title,subject:master.subject,grade:master.grade,term:master.term,description:master.description||null,active:master.active!==false,archived:false,created_by:currentTeacher.user_id,source_workbook_id:master.id,custom_student_id:student.id}).select().single();
    if(wr.error)throw wr.error;newBook=wr.data;
    const {data:acts,error:ae}=await sb.from('activities').select('*').eq('workbook_id',master.id).order('created_at');if(ae)throw ae;
    const actIds=(acts||[]).map(a=>a.id);let files=[];if(actIds.length){const fr=await sb.from('activity_files').select('*').in('activity_id',actIds).order('sort_order');if(fr.error)throw fr.error;files=fr.data||[];}
    for(const a of acts||[]){
      const nr=await sb.from('activities').insert({workbook_id:newBook.id,unit:a.unit,title:a.title,instructions:a.instructions,total_marks:a.total_marks,questions:a.questions||[],memo:a.memo||[],memo_released:a.memo_released,date_loaded:a.date_loaded,due_date:a.due_date,created_by:currentTeacher.user_id,source_activity_id:a.id}).select().single();if(nr.error)throw nr.error;
      for(const f of files.filter(x=>x.activity_id===a.id)){
        if(f.external_url){const ir=await sb.from('activity_files').insert({activity_id:nr.data.id,kind:f.kind,storage_path:null,external_url:f.external_url,file_name:f.file_name,mime_type:f.mime_type||'text/html',sort_order:f.sort_order||0});if(ir.error)throw ir.error;continue;}
        const url=await signed(f.storage_path,1200),res=await fetch(url);if(!res.ok)throw new Error(`Could not copy ${f.file_name}.`);const blob=await res.blob();const path=`activity-${f.kind}/${nr.data.id}/${uuid()}_${safeFile(f.file_name)}`;await teacherUpload(new File([blob],f.file_name,{type:f.mime_type||blob.type||inferMime(f.file_name)}),path);copiedPaths.push(path);const ir=await sb.from('activity_files').insert({activity_id:nr.data.id,kind:f.kind,storage_path:path,external_url:null,file_name:f.file_name,mime_type:f.mime_type||blob.type||null,sort_order:f.sort_order||0});if(ir.error)throw ir.error;
      }
      const move=await sb.from('submissions').update({activity_id:nr.data.id}).eq('student_id',student.id).eq('activity_id',a.id);if(move.error)throw move.error;
    }
    const ar=await sb.from('workbook_assignments').update({custom_workbook_id:newBook.id}).eq('id',assignment.id);if(ar.error)throw ar.error;
    closeModal();toast(`Personalized workbook created for ${student.name}.`);location.hash='workbooks:'+newBook.id;
  }catch(err){console.error(err);if(newBook?.id)await sb.from('workbooks').delete().eq('id',newBook.id);if(copiedPaths.length)await sb.storage.from(BUCKET).remove(copiedPaths);setBusy(btn,false);toast(err.message||String(err),true);}
}

async function pageWorkbooks(){
  const {data:books,error}=await sb.from('workbooks').select('*, activities(count)').is('custom_student_id',null).order('grade').order('term').order('subject').order('title'); if(error) throw error;
  const current=(books||[]).filter(w=>!w.archived).length, archived=(books||[]).filter(w=>w.archived).length;
  const savedView=localStorage.getItem('sntWorkbookView')==='list'?'list':'tile';
  const cards=(books||[]).map(w=>`<div class="card workbook-card" data-title="${esc((w.title+' '+w.subject).toLowerCase())}" data-grade="${w.grade}" data-term="${w.term}" data-archived="${!!w.archived}"><div class="wb-meta"><div class="row"><span class="pill">Grade ${w.grade}</span><span class="pill blue">Term ${w.term}</span>${w.archived?'<span class="pill amber">Archived</span>':''}</div><div class="small muted">${esc(w.subject)}</div></div><div class="wb-main"><div class="workbook-title">${esc(w.title)}</div><div class="muted small wb-description">${esc(w.description||'No description')}</div></div><div class="wb-stats"><div>${w.activities?.[0]?.count||0} activities</div>${w.active?'<span class="pill green">Active</span>':'<span class="pill">Inactive</span>'}</div><div class="row wb-actions"><button class="btn" data-open-wb="${w.id}">Open</button><button class="btn ${w.archived?'secondary':'amber'}" data-archive-wb="${w.id}" data-state="${!!w.archived}">${w.archived?'Restore':'Archive'}</button></div></div>`).join('');
  teacherShell(`<div class="page-head"><div><h1>Workbooks</h1><p>${current} current workbook${current===1?'':'s'} · ${archived} archived. Archive old workbooks to keep this page easy to work with.</p></div><button id="addWorkbook" class="btn">＋ New workbook</button></div><div class="toolbar workbook-toolbar"><input id="wbSearch" placeholder="Search title or subject…"><select id="wbGrade"><option value="">All grades</option>${[4,5,6,7,8,9,10,11,12].map(g=>`<option>${g}</option>`).join('')}</select><select id="wbTerm"><option value="">All terms</option>${[1,2,3,4].map(t=>`<option value="${t}">Term ${t}</option>`).join('')}</select><select id="wbArchive"><option value="current">Current workbooks</option><option value="archived">Archived only</option><option value="all">Current + archived</option></select><div class="view-switch"><button type="button" class="btn secondary sm" id="tileView" aria-label="Tile view">▦ Tiles</button><button type="button" class="btn secondary sm" id="listView" aria-label="List view">☰ List</button></div></div><div id="wbGrid" class="workbook-collection ${savedView==='list'?'list-view':'tile-view'}">${cards}</div><div id="wbNoResults" class="empty hidden">No workbooks match these filters.</div>`,'workbooks');
  const applyView=view=>{const grid=$('#wbGrid');grid.classList.toggle('list-view',view==='list');grid.classList.toggle('tile-view',view!=='list');$('#tileView').classList.toggle('active',view!=='list');$('#listView').classList.toggle('active',view==='list');localStorage.setItem('sntWorkbookView',view);};
  const filter=()=>{const q=$('#wbSearch').value.toLowerCase(),g=$('#wbGrade').value,t=$('#wbTerm').value,a=$('#wbArchive').value;let shown=0;$$('#wbGrid .workbook-card').forEach(c=>{const archiveOk=a==='all'||(a==='archived'&&c.dataset.archived==='true')||(a==='current'&&c.dataset.archived==='false');const ok=(!q||c.dataset.title.includes(q))&&(!g||c.dataset.grade===g)&&(!t||c.dataset.term===t)&&archiveOk;c.classList.toggle('hidden',!ok);if(ok)shown++;});$('#wbNoResults').classList.toggle('hidden',shown!==0);};
  $('#wbSearch').oninput=filter;$('#wbGrade').onchange=filter;$('#wbTerm').onchange=filter;$('#wbArchive').onchange=filter;
  $('#tileView').onclick=()=>applyView('tile');$('#listView').onclick=()=>applyView('list');applyView(savedView);filter();
  $('#addWorkbook').onclick=()=>workbookModal(); $$('[data-open-wb]').forEach(b=>b.onclick=()=>location.hash='workbooks:'+b.dataset.openWb);
  $$('[data-archive-wb]').forEach(b=>b.onclick=()=>setWorkbookArchived(b.dataset.archiveWb,b.dataset.state==='true'));
}
async function setWorkbookArchived(id,isArchived){
  const verb=isArchived?'restore':'archive';
  const message=isArchived?'Restore this workbook to the normal workbook list?':'Archive this workbook? Existing students who already have it assigned will keep access, but it will be hidden from normal workbook browsing and new allocations.';
  if(!confirm(message))return;
  const {error}=await sb.from('workbooks').update({archived:!isArchived,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message,true);toast(`Workbook ${verb}d.`);pageWorkbooks();
}
function workbookModal(w){
  modal(`<h2>${w?'Edit workbook':'Create workbook'}</h2><form id="wbForm"><div class="form-grid"><div class="field"><label>Subject</label><input name="subject" required value="${esc(w?.subject||'')}"></div><div class="field"><label>Workbook title</label><input name="title" required value="${esc(w?.title||'')}"></div><div class="field"><label>Grade</label><select name="grade">${[4,5,6,7,8,9,10,11,12].map(g=>`<option value="${g}" ${Number(w?.grade)===g?'selected':''}>Grade ${g}</option>`).join('')}</select></div><div class="field"><label>Term</label><select name="term">${[1,2,3,4].map(t=>`<option value="${t}" ${Number(w?.term||1)===t?'selected':''}>Term ${t}</option>`).join('')}</select></div><div class="field wide"><label>Description</label><textarea name="description">${esc(w?.description||'')}</textarea></div><div class="field"><label>Status</label><select name="active"><option value="true" ${w?.active!==false?'selected':''}>Active</option><option value="false" ${w?.active===false?'selected':''}>Inactive</option></select></div></div><div class="modal-actions"><button type="button" class="btn secondary" data-close>Cancel</button><button class="btn">Save workbook</button></div></form>`);
  $('#wbForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;setBusy(btn,true);const f=new FormData(e.currentTarget);const row={subject:f.get('subject').trim(),title:f.get('title').trim(),grade:Number(f.get('grade')),term:Number(f.get('term')),description:f.get('description').trim()||null,active:f.get('active')==='true',updated_at:new Date().toISOString()};const r=w?await sb.from('workbooks').update(row).eq('id',w.id):await sb.from('workbooks').insert({...row,archived:false,created_by:currentTeacher.user_id});if(r.error){setBusy(btn,false);return toast(r.error.message,true);}closeModal();toast('Workbook saved.');w?pageWorkbook(w.id):pageWorkbooks();};
}

async function pageWorkbook(id){
  const [{data:w,error},{data:acts},{data:files}] = await Promise.all([sb.from('workbooks').select('*').eq('id',id).single(),sb.from('activities').select('*').eq('workbook_id',id).order('date_loaded').order('created_at'),sb.from('activity_files').select('*').in('activity_id',(await sb.from('activities').select('id').eq('workbook_id',id)).data?.map(x=>x.id)||['00000000-0000-0000-0000-000000000000'])]); if(error) throw error;
  let customStudent=null;if(w.custom_student_id){const r=await sb.from('students').select('id,name,grade').eq('id',w.custom_student_id).maybeSingle();customStudent=r.data||null;}
  const personal=!!customStudent;
  teacherShell(`<div class="page-head"><div><div class="row"><button class="btn secondary sm" id="backWb">← ${personal?'Students':'Workbooks'}</button><span class="pill">Grade ${w.grade}</span><span class="pill blue">Term ${w.term}</span>${personal?`<span class="pill green">Personalized for ${esc(customStudent.name)}</span>`:''}</div><h1 style="margin-top:.6rem">${esc(w.subject)} — ${esc(w.title)}</h1><p>${esc(w.description||'')}</p></div><div class="row">${personal&&w.source_workbook_id?'<button id="openMasterWb" class="btn secondary">Open master</button>':''}<button id="exportThis" class="btn secondary">Export workbook</button><button id="editWb" class="btn secondary">Edit</button><button id="addActivity" class="btn">＋ Activity</button></div></div>${personal?`<div class="info-box" style="margin-bottom:1rem"><strong>Student-only copy:</strong> every change on this page affects <strong>${esc(customStudent.name)}</strong> only. The master workbook and other learners remain unchanged.</div>`:''}<div class="stack">${acts?.map(a=>activityTeacherCard(a,(files||[]).filter(f=>f.activity_id===a.id))).join('')||'<div class="empty">No activities yet. Add the first activity.</div>'}</div>`,personal?'students':'workbooks');
  $('#backWb').onclick=()=>location.hash=personal?'students':'workbooks';if($('#openMasterWb'))$('#openMasterWb').onclick=()=>location.hash='workbooks:'+w.source_workbook_id;$('#editWb').onclick=()=>workbookModal(w);$('#addActivity').onclick=()=>activityModal(w,null,[]);$('#exportThis').onclick=e=>exportWorkbookPackage(w.id,e.currentTarget);
  $$('[data-edit-activity]').forEach(b=>b.onclick=()=>{const a=acts.find(x=>x.id===b.dataset.editActivity);if(!a)return toast('Could not load this activity. Refresh and try again.',true);activityModal(w,a,(files||[]).filter(f=>f.activity_id===a.id));});
  $$('[data-toggle-memo]').forEach(b=>b.onclick=()=>toggleMemo(b.dataset.toggleMemo,b.dataset.state==='true'));
  $$('[data-delete-activity]').forEach(b=>b.onclick=()=>deleteActivity(b.dataset.deleteActivity,w.id));
  $$('[data-view-file-id]').forEach(b=>{const f=(files||[]).find(x=>x.id===b.dataset.viewFileId);b.onclick=()=>f&&openTeacherAttachment(f);});
}

function activityTeacherCard(a,files){ const qf=files.filter(f=>f.kind==='question'),mf=files.filter(f=>f.kind==='memo');const qButton=f=>`<button class="btn secondary sm" data-view-file-id="${f.id}">${f.external_url?'🌐':'📎'} ${esc(f.file_name)}</button>`;const mButton=f=>`<button class="btn secondary sm" data-view-file-id="${f.id}">${f.external_url?'🌐':'🔐'} ${esc(f.file_name)}</button>`;return `<div class="activity ${isOverdue(a.due_date)?'overdue':''}"><div class="row spread"><div><div class="small muted">${esc(a.unit||'Activity')}</div><h3 style="margin:.15rem 0">${esc(a.title)}</h3></div><div class="row">${a.memo_released?'<span class="pill green">Memo released</span>':'<span class="pill">Memo hidden</span>'}${isOverdue(a.due_date)?'<span class="pill red">Due date passed</span>':''}</div></div><div class="row small muted"><span>Loaded: <strong>${fmtDate(a.date_loaded)}</strong></span><span>Due: <strong>${fmtDate(a.due_date)}</strong></span><span>${a.total_marks||0} marks</span><span>${qf.length} question files/links</span><span>${mf.length} memo files/links</span></div><p>${linkifyNl2br(a.instructions||'')}</p><ol class="question-list">${(a.questions||[]).map(q=>`<li>${linkify(q)}</li>`).join('')}</ol>${qf.length?`<div class="row" style="margin-top:.6rem"><span class="small muted">Questions:</span>${qf.map(qButton).join('')}</div>`:''}${mf.length?`<div class="row" style="margin-top:.45rem"><span class="small muted">Memo:</span>${mf.map(mButton).join('')}</div>`:''}<div class="row" style="margin-top:.8rem"><button class="btn secondary sm" data-edit-activity="${a.id}">Edit</button><button class="btn ${a.memo_released?'amber':'secondary'} sm" data-toggle-memo="${a.id}" data-state="${a.memo_released}">${a.memo_released?'Hide memo':'Reveal memo'}</button><button class="btn danger sm" data-delete-activity="${a.id}">Delete</button></div></div>`; }
async function toggleMemo(id,state){const {error}=await sb.from('activities').update({memo_released:!state,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message,true);toast(!state?'Memo released.':'Memo hidden.');renderTeacherRoute();}
async function deleteActivity(id,wbid){if(!confirm('Delete this activity and all its submissions/files?'))return;const {data:paths}=await sb.from('all_file_paths').select('storage_path').eq('activity_id',id);const actual=(paths||[]).map(x=>x.storage_path).filter(Boolean);if(actual.length)await sb.storage.from(BUCKET).remove(actual);const {error}=await sb.from('activities').delete().eq('id',id);if(error)return toast(error.message,true);toast('Activity deleted.');pageWorkbook(wbid);}
async function openTeacherFile(path){try{window.open(await signed(path),'_blank','noopener');}catch(e){toast(e.message,true);}}
async function openTeacherAttachment(file){if(file?.external_url){window.open(file.external_url,'_blank','noopener,noreferrer');return;}if(file?.storage_path)return openTeacherFile(file.storage_path);toast('This attachment has no usable file or web link.',true);}
function activityModal(w,a,files){
  const qf=files.filter(f=>f.kind==='question'),mf=files.filter(f=>f.kind==='memo');
  modal(`<h2>${a?'Edit':'Add'} activity — ${esc(w.title)}</h2><form id="activityForm"><div class="form-grid"><div class="field"><label>Unit / section</label><input name="unit" value="${esc(a?.unit||'')}"></div><div class="field"><label>Activity title</label><input name="title" required value="${esc(a?.title||'')}"></div><div class="field"><label>Date loaded</label><input type="date" name="date_loaded" value="${esc(a?.date_loaded||todayISO())}"></div><div class="field"><label>Date due</label><input type="date" name="due_date" value="${esc(a?.due_date||'')}"></div><div class="field"><label>Total marks</label><input type="number" min="0" step="0.5" name="total_marks" value="${esc(a?.total_marks||0)}"></div><div class="field"><label>Memo</label><select name="memo_released"><option value="false" ${!a?.memo_released?'selected':''}>Hidden</option><option value="true" ${a?.memo_released?'selected':''}>Revealed</option></select></div><div class="field wide"><label>Instructions</label><textarea name="instructions">${esc(a?.instructions||'')}</textarea></div><div class="field wide"><label>Questions — one per line</label><textarea name="questions" style="min-height:150px">${esc((a?.questions||[]).join('\n'))}</textarea></div><div class="field wide"><label>Memo / answers — one per line</label><textarea name="memo" style="min-height:150px">${esc((a?.memo||[]).join('\n'))}</textarea></div><div class="field wide"><label>Question images / PDFs</label><input type="file" name="question_files" multiple accept="image/*,application/pdf"><div class="hint">Upload files from this device. New files are added to existing attachments. Max ${cfg.MAX_FILE_MB||10} MB each.</div>${fileChips(qf)}</div><div class="field wide"><label>Question web files / Google Docs</label><textarea name="question_links" placeholder="https://docs.google.com/document/d/...\nSource notes | https://example.com/file"></textarea><div class="hint">Paste one public/viewable web link per line. Optional format: <strong>Name | https://link</strong>.</div></div><div class="field wide"><label>Memo images / PDFs</label><input type="file" name="memo_files" multiple accept="image/*,application/pdf"><div class="hint">Uploaded memo files stay hidden from learners until the memo is revealed.</div>${fileChips(mf)}</div><div class="field wide"><label>Memo web files / Google Docs</label><textarea name="memo_links" placeholder="https://docs.google.com/document/d/...\nWorked memo | https://example.com/memo"></textarea><div class="hint"><strong>These links stay hidden from learners until you reveal the memo.</strong> The Google Doc itself should be set to viewable by anyone with the link.</div></div></div><div class="modal-actions"><button type="button" class="btn secondary" data-close>Cancel</button><button class="btn">Save activity</button></div></form>`);
  $$('[data-open-existing]').forEach(b=>b.onclick=()=>{const f=files.find(x=>x.id===b.dataset.openExisting);if(f)openTeacherAttachment(f);});
  $$('[data-delete-file]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this attachment?'))return;const f=files.find(x=>x.id===b.dataset.deleteFile);if(f?.storage_path)await deleteStorage(f.storage_path);await sb.from('activity_files').delete().eq('id',f.id);b.closest('.file-chip').remove();toast('Attachment deleted.');});
  $('#activityForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const btn=e.submitter;const f=new FormData(form);const questionFiles=[...form.elements.question_files.files];const memoFiles=[...form.elements.memo_files.files];let questionLinks,memoLinks;try{questionLinks=parseWebAttachments(f.get('question_links'));memoLinks=parseWebAttachments(f.get('memo_links'));}catch(err){return toast(err.message||String(err),true);}setBusy(btn,true,'Saving…');try{const row={workbook_id:w.id,unit:f.get('unit').trim()||null,title:f.get('title').trim(),instructions:f.get('instructions').trim()||null,total_marks:Number(f.get('total_marks')||0),questions:parseLines(f.get('questions')),memo:parseLines(f.get('memo')),memo_released:f.get('memo_released')==='true',date_loaded:f.get('date_loaded')||null,due_date:f.get('due_date')||null,updated_at:new Date().toISOString()};let aid=a?.id;if(a){const r=await sb.from('activities').update(row).eq('id',a.id);if(r.error)throw r.error;}else{const r=await sb.from('activities').insert({...row,created_by:currentTeacher.user_id}).select().single();if(r.error)throw r.error;aid=r.data.id;}await uploadActivityFiles(aid,questionFiles,'question');await uploadActivityFiles(aid,memoFiles,'memo');await addActivityLinks(aid,questionLinks,'question');await addActivityLinks(aid,memoLinks,'memo');closeModal();toast('Activity saved.');pageWorkbook(w.id);}catch(err){setBusy(btn,false);toast(err.message||String(err),true);}};
}
function fileChips(files){return files.length?`<div class="file-list" style="margin-top:.5rem">${files.map(f=>`<div class="file-chip"><span>${f.external_url?'🌐':'📎'} ${esc(f.file_name)}</span><span class="row"><button type="button" class="btn secondary sm" data-open-existing="${f.id}">Open</button><button type="button" class="btn danger sm" data-delete-file="${f.id}">Delete</button></span></div>`).join('')}</div>`:'';}
async function uploadActivityFiles(aid,files,kind){for(const file of files){const path=`activity-${kind}/${aid}/${uuid()}_${safeFile(file.name)}`;await teacherUpload(file,path);const {error}=await sb.from('activity_files').insert({activity_id:aid,kind,storage_path:path,external_url:null,file_name:file.name,mime_type:file.type||inferMime(file.name)});if(error){await deleteStorage(path);throw error;}}}
async function addActivityLinks(aid,links,kind){for(const item of links||[]){const {error}=await sb.from('activity_files').insert({activity_id:aid,kind,storage_path:null,external_url:item.url,file_name:item.label,mime_type:'text/html'});if(error)throw error;}}

async function pageOutstanding(){
  const [{data:students,error:se},{data:assignments,error:ae},{data:books,error:be},{data:activities,error:xe},{data:submissions,error:sue}] = await Promise.all([
    sb.from('students').select('id,name,grade,active').eq('active',true).order('grade').order('name'),
    sb.from('workbook_assignments').select('id,student_id,workbook_id,custom_workbook_id'),
    sb.from('workbooks').select('id,title,subject,grade,term,active,custom_student_id,source_workbook_id'),
    sb.from('activities').select('id,workbook_id,unit,title,date_loaded,due_date,total_marks').order('due_date'),
    sb.from('submissions').select('id,student_id,activity_id,status,submitted_at')
  ]); if(se||ae||be||xe||sue) throw (se||ae||be||xe||sue);
  const studentMap=new Map((students||[]).map(x=>[x.id,x])),bookMap=new Map((books||[]).map(x=>[x.id,x])),subMap=new Map((submissions||[]).map(x=>[`${x.student_id}:${x.activity_id}`,x]));
  const actsByBook=new Map();for(const a of activities||[]){if(!actsByBook.has(a.workbook_id))actsByBook.set(a.workbook_id,[]);actsByBook.get(a.workbook_id).push(a);}
  const rows=[];for(const asg of assignments||[]){const st=studentMap.get(asg.student_id);if(!st)continue;const effectiveId=asg.custom_workbook_id||asg.workbook_id,wb=bookMap.get(effectiveId);if(!wb?.active)continue;for(const act of actsByBook.get(effectiveId)||[]){const sub=subMap.get(`${st.id}:${act.id}`);if(sub && !['corrections','redo'].includes(sub.status))continue;const kind=!sub?'not-submitted':sub.status;rows.push({student:st,workbook:wb,activity:act,submission:sub,kind});}}
  rows.sort((a,b)=>(a.activity.due_date||'9999-12-31').localeCompare(b.activity.due_date||'9999-12-31')||a.student.grade-b.student.grade||a.student.name.localeCompare(b.student.name));
  const dueDates=[...new Set(rows.map(r=>r.activity.due_date).filter(Boolean))].sort(),studentOptions=[...new Map(rows.map(r=>[r.student.id,r.student])).values()].sort((a,b)=>a.grade-b.grade||a.name.localeCompare(b.name));
  const rowHtml=rows.map((r,i)=>{const due=r.activity.due_date||'',dateState=!due?'none':due<todayISO()?'overdue':due===todayISO()?'today':'upcoming';const status=r.kind==='not-submitted'?'<span class="pill red">Not submitted</span>':r.kind==='corrections'?'<span class="pill amber">Corrections required</span>':'<span class="pill red">Redo required</span>';return `<tr data-out-row data-grade="${r.student.grade}" data-student="${r.student.id}" data-due="${due}" data-date-state="${dateState}" data-kind="${r.kind}"><td><strong>${esc(r.student.name)}</strong><div class="small muted">Grade ${r.student.grade}</div></td><td>${esc(r.workbook.subject)}<div class="small muted">${esc(r.workbook.title)} · T${r.workbook.term}${r.workbook.custom_student_id?' · Personalized':''}</div></td><td><strong>${esc(r.activity.title)}</strong><div class="small muted">${esc(r.activity.unit||'')}</div></td><td>${fmtDate(r.activity.date_loaded)}</td><td><strong class="${dateState==='overdue'?'text-danger':''}">${fmtDate(r.activity.due_date)}</strong></td><td>${status}</td><td><button class="btn secondary sm" data-open-out-wb="${r.workbook.id}">Open workbook</button>${r.submission?` <button class="btn sm" data-open-out-sub="${r.submission.id}">Review</button>`:''}</td></tr>`;}).join('');
  teacherShell(`<div class="page-head"><div><h1>Outstanding work</h1><p>Overall work still owed by learners, including work not submitted, corrections and redo requests.</p></div></div><div class="grid cards outstanding-stats"><div class="card"><div class="muted">Outstanding</div><div class="stat" id="outTotal">0</div></div><div class="card"><div class="muted">Overdue</div><div class="stat" id="outOverdue">0</div></div><div class="card"><div class="muted">Not submitted</div><div class="stat" id="outNotSubmitted">0</div></div><div class="card"><div class="muted">Corrections / redo</div><div class="stat" id="outCorrections">0</div></div></div><div class="toolbar" style="margin-top:1rem"><select id="outGrade"><option value="">All grades</option>${[4,5,6,7,8,9,10,11,12].map(g=>`<option value="${g}">Grade ${g}</option>`).join('')}</select><select id="outDate"><option value="">All dates / Overall</option><option value="state:overdue">Overdue</option><option value="state:today">Due today</option><option value="state:upcoming">Upcoming</option><option value="state:none">No due date</option>${dueDates.length?'<option disabled>──────────</option>':''}${dueDates.map(d=>`<option value="date:${d}">${fmtDate(d)}</option>`).join('')}</select><select id="outStudent"><option value="">All students</option>${studentOptions.map(st=>`<option value="${st.id}">Grade ${st.grade} — ${esc(st.name)}</option>`).join('')}</select></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Workbook</th><th>Activity</th><th>Loaded</th><th>Due</th><th>Outstanding status</th><th>Action</th></tr></thead><tbody id="outRows">${rowHtml||'<tr><td colspan="7"><div class="empty">Excellent — there is no outstanding learner work for the current assignments.</div></td></tr>'}</tbody></table></div>`,'outstanding');
  const apply=()=>{const g=$('#outGrade').value,d=$('#outDate').value,st=$('#outStudent').value;let visible=[];$$('[data-out-row]').forEach(r=>{let ok=(!g||r.dataset.grade===g)&&(!st||r.dataset.student===st);if(ok&&d){if(d.startsWith('state:'))ok=r.dataset.dateState===d.slice(6);else if(d.startsWith('date:'))ok=r.dataset.due===d.slice(5);}r.classList.toggle('hidden',!ok);if(ok)visible.push(r);});$('#outTotal').textContent=visible.length;$('#outOverdue').textContent=visible.filter(r=>r.dataset.dateState==='overdue').length;$('#outNotSubmitted').textContent=visible.filter(r=>r.dataset.kind==='not-submitted').length;$('#outCorrections').textContent=visible.filter(r=>['corrections','redo'].includes(r.dataset.kind)).length;};
  $('#outGrade').onchange=apply;$('#outDate').onchange=apply;$('#outStudent').onchange=apply;apply();
  $$('[data-open-out-wb]').forEach(b=>b.onclick=()=>location.hash='workbooks:'+b.dataset.openOutWb);
  $$('[data-open-out-sub]').forEach(b=>b.onclick=async()=>{const {data:full,error}=await sb.from('submissions').select('*,students(id,name,grade),activities(id,title,total_marks,date_loaded,due_date,workbook_id,workbooks(id,title,subject,grade,term))').eq('id',b.dataset.openOutSub).single();if(error)return toast(error.message,true);reviewSubmission(full);});
}

async function pageSubmissions(){
  const {data:subs,error}=await sb.from('submissions').select('*,students(id,name,grade),activities(id,title,total_marks,date_loaded,due_date,workbook_id,workbooks(id,title,subject,grade,term))').order('submitted_at',{ascending:false}); if(error) throw error;
  teacherShell(`<div class="page-head"><div><h1>Student submissions</h1><p>Review scripts, build AI marking PDFs, return corrected work and marks.</p></div></div><div class="toolbar"><input id="subSearch" placeholder="Search student/activity…"><select id="subTerm"><option value="">All terms</option>${[1,2,3,4].map(t=>`<option value="${t}">Term ${t}</option>`).join('')}</select><select id="subStatus"><option value="">All statuses</option><option value="submitted">Submitted</option><option value="marked">Marked</option><option value="corrections">Corrections required</option><option value="redo">Redo required</option></select></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Workbook</th><th>Activity</th><th>Submitted</th><th>Status</th><th>Mark</th><th>Actions</th></tr></thead><tbody id="subRows">${subs.map(s=>`<tr data-search="${esc((s.students?.name+' '+s.activities?.title+' '+s.activities?.workbooks?.title+' '+s.activities?.workbooks?.subject).toLowerCase())}" data-term="${s.activities?.workbooks?.term}" data-status="${esc(s.status)}"><td><strong>${esc(s.students?.name)}</strong><div class="small muted">Grade ${s.students?.grade}</div></td><td>${esc(s.activities?.workbooks?.subject)}<div class="small muted">${esc(s.activities?.workbooks?.title)} · T${s.activities?.workbooks?.term}</div></td><td>${esc(s.activities?.title)}</td><td>${fmtDateTime(s.submitted_at)}</td><td>${statusPill(s.status)}</td><td>${s.score==null?'—':`${esc(s.score)}/${esc(s.activities?.total_marks)} (${moneylessPercent(s.score,s.activities?.total_marks)}%)`}</td><td><div class="row"><button class="btn secondary sm" data-review="${s.id}">Review</button><button class="btn sm" data-pack="${s.id}">AI PDF</button></div></td></tr>`).join('')||'<tr><td colspan="7">No submissions yet.</td></tr>'}</tbody></table></div>`,'submissions');
  const filter=()=>{const q=$('#subSearch').value.toLowerCase(),t=$('#subTerm').value,st=$('#subStatus').value;$$('#subRows tr[data-search]').forEach(r=>r.classList.toggle('hidden',!((!q||r.dataset.search.includes(q))&&(!t||r.dataset.term===t)&&(!st||r.dataset.status===st))));};$('#subSearch').oninput=filter;$('#subTerm').onchange=filter;$('#subStatus').onchange=filter;
  $$('[data-review]').forEach(b=>b.onclick=()=>reviewSubmission(subs.find(s=>s.id===b.dataset.review))); $$('[data-pack]').forEach(b=>b.onclick=()=>makeMarkingPack(subs.find(s=>s.id===b.dataset.pack),b));
}
async function reviewSubmission(s){
  const [{data:script},{data:corrected}] = await Promise.all([sb.from('submission_files').select('*').eq('submission_id',s.id).order('page_order'),sb.from('corrected_files').select('*').eq('submission_id',s.id).order('created_at')]);
  const typed=Array.isArray(s.typed_answers)?s.typed_answers:[];
  modal(`<h2>${esc(s.students.name)} — ${esc(s.activities.title)}</h2><div class="row"><span class="pill">${esc(s.activities.workbooks.subject)}</span><span class="pill blue">Term ${s.activities.workbooks.term}</span><span>${fmtDateTime(s.submitted_at)}</span></div><h3>Typed answers</h3>${typed.some(x=>String(x||'').trim())?`<div class="typed-review">${typed.map((ans,i)=>String(ans||'').trim()?`<div class="typed-review-item"><strong>Answer ${i+1}</strong><div>${nl2br(ans)}</div></div>`:'').join('')}</div>`:'<div class="empty">No typed answers. The learner may have submitted handwritten pages only.</div>'}<h3>Uploaded script</h3>${script?.length?`<div class="file-list">${script.map(f=>`<div class="file-chip"><span>📄 ${esc(f.file_name)}</span><button class="btn secondary sm" data-view-script="${esc(f.storage_path)}">Open</button></div>`).join('')}</div>`:'<div class="empty">No uploaded pages. The learner may have typed answers only.</div>'}<form id="markForm" style="margin-top:1rem"><div class="form-grid"><div class="field"><label>Score / ${s.activities.total_marks}</label><input type="number" name="score" min="0" max="${s.activities.total_marks||9999}" step="0.5" value="${esc(s.score??'')}"></div><div class="field"><label>Status</label><select name="status"><option value="marked" ${s.status==='marked'?'selected':''}>Marked / complete</option><option value="corrections" ${s.status==='corrections'?'selected':''}>Corrections required</option><option value="redo" ${s.status==='redo'?'selected':''}>Redo activity</option><option value="submitted" ${s.status==='submitted'?'selected':''}>Submitted / awaiting marking</option></select></div><div class="field wide"><label>Teacher comment</label><textarea name="teacher_comment">${esc(s.teacher_comment||'')}</textarea></div><div class="field wide"><label>Upload corrected work</label><input type="file" name="corrected" multiple accept="image/*,application/pdf">${corrected?.length?`<div class="file-list" style="margin-top:.5rem">${corrected.map(f=>`<div class="file-chip"><span>✅ ${esc(f.file_name)}</span><button type="button" class="btn secondary sm" data-view-corrected="${esc(f.storage_path)}">Open</button></div>`).join('')}</div>`:''}</div></div><div class="modal-actions"><button type="button" class="btn secondary" data-close>Close</button><button class="btn">Save marking</button></div></form>`);
  $$('[data-view-script],[data-view-corrected]').forEach(b=>b.onclick=()=>openTeacherFile(b.dataset.viewScript||b.dataset.viewCorrected));
  $('#markForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const btn=e.submitter;const f=new FormData(form);const correctedFiles=[...form.elements.corrected.files];setBusy(btn,true,'Saving…');try{const score=f.get('score')===''?null:Number(f.get('score'));const {error}=await sb.from('submissions').update({score,status:f.get('status'),teacher_comment:f.get('teacher_comment').trim()||null,marked_at:new Date().toISOString(),marked_by:currentTeacher.user_id}).eq('id',s.id);if(error)throw error;for(const file of correctedFiles){const path=`corrected/${s.students.id}/${s.activities.id}/${uuid()}_${safeFile(file.name)}`;await teacherUpload(file,path);const r=await sb.from('corrected_files').insert({submission_id:s.id,storage_path:path,file_name:file.name,mime_type:file.type||inferMime(file.name)});if(r.error)throw r.error;}closeModal();toast('Marking saved and learner hub updated.');pageSubmissions();}catch(err){setBusy(btn,false);toast(err.message,true);}};
}

async function makeMarkingPack(s,btn){
  setBusy(btn,true,'Building…');
  try{
    const [{data:a},{data:af},{data:sf}] = await Promise.all([sb.from('activities').select('*,workbooks(*)').eq('id',s.activities.id).single(),sb.from('activity_files').select('*').eq('activity_id',s.activities.id).order('sort_order'),sb.from('submission_files').select('*').eq('submission_id',s.id).order('page_order')]);
    const PDF=window.PDFLib; if(!PDF) throw new Error('PDF library did not load.'); const doc=await PDF.PDFDocument.create(); const font=await doc.embedFont(PDF.StandardFonts.Helvetica); const bold=await doc.embedFont(PDF.StandardFonts.HelveticaBold);
    addTextPages(doc,font,bold,`${a.workbooks.subject} — ${a.workbooks.title}\n${a.title}`, [`Student: ${s.students.name}`,`Grade: ${s.students.grade} | Term: ${a.workbooks.term}`,`Loaded: ${fmtDate(a.date_loaded)} | Due: ${fmtDate(a.due_date)}`,`Total marks: ${a.total_marks}`,'','QUESTIONS',...(a.questions||[]).map((q,i)=>`${i+1}. ${q}`),'','OFFICIAL MEMO',...(a.memo||[]).map((m,i)=>`${i+1}. ${m}`)]);
    const append=async(f,label)=>{
      if(f.external_url){addTextPages(doc,font,bold,label,[`Web attachment: ${f.file_name}`,f.external_url]);return;}
      if(!f.storage_path){addTextPages(doc,font,bold,label,[`Attachment unavailable: ${f.file_name}`]);return;}
      const url=await signed(f.storage_path,900);const res=await fetch(url);const blob=await res.blob();const bytes=new Uint8Array(await blob.arrayBuffer());
      if((f.mime_type||'').includes('pdf')||f.file_name.toLowerCase().endsWith('.pdf')){
        const src=await PDF.PDFDocument.load(bytes);const pages=await doc.copyPages(src,src.getPageIndices());pages.forEach(p=>doc.addPage(p));return;
      }
      if((f.mime_type||'').startsWith('image/')||/\.(png|jpe?g|webp|hei[cf])$/i.test(f.file_name)){
        try{
          let img;const isPng=(f.mime_type||'').includes('png')||/\.png$/i.test(f.file_name);const isJpg=(f.mime_type||'').includes('jpeg')||/\.jpe?g$/i.test(f.file_name);
          if(isPng)img=await doc.embedPng(bytes);else if(isJpg)img=await doc.embedJpg(bytes);else{const bmp=await createImageBitmap(blob);const canvas=document.createElement('canvas');canvas.width=bmp.width;canvas.height=bmp.height;canvas.getContext('2d').drawImage(bmp,0,0);const pngBlob=await new Promise((resolve,reject)=>canvas.toBlob(x=>x?resolve(x):reject(new Error('Image conversion failed.')),'image/png'));img=await doc.embedPng(new Uint8Array(await pngBlob.arrayBuffer()));bmp.close?.();}
          const page=doc.addPage([595,842]);page.drawText(label,{x:36,y:810,size:12,font:bold});const maxW=523,maxH=750,sc=Math.min(maxW/img.width,maxH/img.height);page.drawImage(img,{x:(595-img.width*sc)/2,y:35,width:img.width*sc,height:img.height*sc});return;
        }catch(err){console.warn('Could not embed image',f.file_name,err);addTextPages(doc,font,bold,label,[`Image attachment could not be embedded: ${f.file_name}`]);return;}
      }
      addTextPages(doc,font,bold,label,[`Attachment: ${f.file_name}`]);
    };
    for(const f of (af||[]).filter(x=>x.kind==='question')) await append(f,'Question/source attachment');
    for(const f of (af||[]).filter(x=>x.kind==='memo')) await append(f,'Memo attachment');
    const typedAnswers=Array.isArray(s.typed_answers)?s.typed_answers:[];
    addTextPages(doc,font,bold,'STUDENT SCRIPT',[`Student: ${s.students.name}`,`Submitted: ${fmtDateTime(s.submitted_at)}`,'',...(typedAnswers.some(x=>String(x||'').trim())?['TYPED ANSWERS',...typedAnswers.map((ans,i)=>String(ans||'').trim()?`${i+1}. ${String(ans).trim()}`:`${i+1}. —`)]:['TYPED ANSWERS: None — learner submitted uploaded pages only.'])]);
    for(const f of sf||[]) await append(f,'Student uploaded script');
    const bytes=await doc.save();downloadBlob(new Blob([bytes],{type:'application/pdf'}),`${safeFile(s.students.name)}_${safeFile(a.title)}_AI_Marking_Pack.pdf`);toast('AI marking PDF created.');
  }catch(e){console.error(e);toast(e.message||String(e),true);}finally{setBusy(btn,false);}
}
function addTextPages(doc,font,bold,title,lines){const size=[595,842],margin=42,maxW=511;let page=doc.addPage(size),y=798;page.drawText(title,{x:margin,y,size:16,font:bold,maxWidth:maxW});y-=34;for(const raw of lines){const txt=String(raw??'');const wrapped=wrapText(txt,88);for(const line of wrapped){if(y<55){page=doc.addPage(size);y=798;}page.drawText(line,{x:margin,y,size:10.5,font,lineHeight:14,maxWidth:maxW});y-=14;}y-=txt===''?6:2;}}
function wrapText(t,max){if(!t)return [''];const words=t.split(/\s+/);const out=[];let line='';for(const w of words){if((line+' '+w).trim().length>max){if(line)out.push(line);line=w;}else line=(line+' '+w).trim();}if(line)out.push(line);return out;}

async function pageBackup(){
  teacherShell(`<div class="page-head"><div><h1>Import / Export</h1><p>Move workbooks between systems and keep a complete off-site backup.</p></div></div><div class="grid cards"><div class="card"><h2>Import workbook package</h2><p class="muted">Import a ZIP previously exported by this app, including activity attachments.</p><input id="importWbZip" type="file" accept=".zip"><div class="row" style="margin-top:.7rem"><button id="doImportZip" class="btn">Import workbook ZIP</button><a class="btn secondary" href="templates/sample_workbook_package.zip" download>Sample ZIP</a></div></div><div class="card"><h2>Import workbook CSV</h2><p class="muted">Fast bulk import for text-based workbooks/activities. Attachments can be added afterwards.</p><input id="importCsv" type="file" accept=".csv,text/csv"><div class="row" style="margin-top:.7rem"><button id="doImportCsv" class="btn">Import CSV</button><a class="btn secondary" href="templates/workbook_import_template.csv" download>CSV template</a></div></div><div class="card"><h2>Export everything</h2><p class="muted">Creates a ZIP containing a database backup JSON plus every question, memo, learner submission and corrected file.</p><button id="fullBackup" class="btn">Download full backup ZIP</button><p class="hint">Large systems can produce a large ZIP and may use significant browser memory.</p></div><div class="card"><h2>Export students</h2><p class="muted">Download learner names, grades, codes and private links as CSV.</p><button id="exportStudents" class="btn secondary">Download students CSV</button></div></div>`,'backup');
  $('#doImportZip').onclick=e=>importWorkbookZip($('#importWbZip').files[0],e.currentTarget); $('#doImportCsv').onclick=e=>importWorkbookCsv($('#importCsv').files[0],e.currentTarget); $('#fullBackup').onclick=e=>fullBackup(e.currentTarget); $('#exportStudents').onclick=exportStudentsCsv;
}
async function exportStudentsCsv(){const {data,error}=await sb.from('students').select('*').order('grade').order('name');if(error)return toast(error.message,true);const rows=data.map(s=>({name:s.name,grade:s.grade,student_code:s.student_code||'',active:s.active,private_link:studentUrl(s)}));downloadBlob(new Blob([toCSV(rows,['name','grade','student_code','active','private_link'])],{type:'text/csv'}),'students.csv');}
async function exportWorkbookPackage(id,btn){setBusy(btn,true,'Exporting…');try{const [{data:w,error},{data:acts}] = await Promise.all([sb.from('workbooks').select('*').eq('id',id).single(),sb.from('activities').select('*').eq('workbook_id',id).order('created_at')]);if(error)throw error;const af=(await sb.from('activity_files').select('*').in('activity_id',acts.map(a=>a.id).length?acts.map(a=>a.id):['00000000-0000-0000-0000-000000000000'])).data||[];const zip=new JSZip();const manifest={format:'snt-workbook-package-v1',exported_at:new Date().toISOString(),workbook:{...w,id:undefined,created_by:undefined,source_workbook_id:undefined,custom_student_id:undefined},activities:[]};for(const a of acts){const item={...a,id:undefined,workbook_id:undefined,created_by:undefined,source_activity_id:undefined,files:[]};for(const f of af.filter(x=>x.activity_id===a.id)){if(f.external_url){item.files.push({kind:f.kind,file_name:f.file_name,mime_type:f.mime_type||'text/html',external_url:f.external_url,sort_order:f.sort_order});continue;}const rel=`files/${a.id}/${uuid()}_${safeFile(f.file_name)}`;const url=await signed(f.storage_path,1200);zip.file(rel,await (await fetch(url)).blob());item.files.push({kind:f.kind,file_name:f.file_name,mime_type:f.mime_type,zip_path:rel,sort_order:f.sort_order});}manifest.activities.push(item);}zip.file('workbook.json',JSON.stringify(manifest,null,2));downloadBlob(await zip.generateAsync({type:'blob'}),`${safeFile(w.subject)}_${safeFile(w.title)}_workbook.zip`);toast('Workbook package exported.');}catch(e){toast(e.message,true);}finally{setBusy(btn,false);}}
async function importWorkbookZip(file,btn){if(!file)return toast('Choose a workbook ZIP first.',true);setBusy(btn,true,'Importing…');try{const zip=await JSZip.loadAsync(file);const mf=zip.file('workbook.json');if(!mf)throw new Error('workbook.json was not found in this ZIP.');const m=JSON.parse(await mf.async('text'));if(m.format!=='snt-workbook-package-v1')throw new Error('This is not an SNT workbook package.');const {data:w,error}=await sb.from('workbooks').insert({...m.workbook,title:m.workbook.title+' (Imported)',archived:false,created_by:currentTeacher.user_id,created_at:new Date().toISOString(),updated_at:new Date().toISOString()}).select().single();if(error)throw error;for(const a of m.activities||[]){const files=a.files||[];delete a.files;delete a.created_at;delete a.updated_at;const {data:na,error:ae}=await sb.from('activities').insert({...a,workbook_id:w.id,created_by:currentTeacher.user_id}).select().single();if(ae)throw ae;for(const f of files){if(f.external_url){const normalized=normalizeExternalUrl(f.external_url);const r=await sb.from('activity_files').insert({activity_id:na.id,kind:f.kind,storage_path:null,external_url:normalized,file_name:f.file_name||externalLinkLabel(normalized),mime_type:f.mime_type||'text/html',sort_order:f.sort_order||0});if(r.error)throw r.error;continue;}const zf=zip.file(f.zip_path);if(!zf)continue;const blob=await zf.async('blob');const path=`activity-${f.kind}/${na.id}/${uuid()}_${safeFile(f.file_name)}`;await teacherUpload(new File([blob],f.file_name,{type:f.mime_type||blob.type}),path);const r=await sb.from('activity_files').insert({activity_id:na.id,kind:f.kind,storage_path:path,external_url:null,file_name:f.file_name,mime_type:f.mime_type||null,sort_order:f.sort_order||0});if(r.error)throw r.error;}}toast('Workbook imported successfully.');pageWorkbooks();}catch(e){toast(e.message||String(e),true);}finally{setBusy(btn,false);}}
async function importWorkbookCsv(file,btn){if(!file)return toast('Choose a CSV first.',true);setBusy(btn,true,'Importing…');try{const rows=parseCSV(await file.text());if(!rows.length)throw new Error('CSV has no data rows.');const grouped=new Map();for(const r of rows){const key=[r.workbook_title,r.subject,r.grade,r.term].join('|');if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(r);}for(const group of grouped.values()){const first=group[0];const {data:w,error}=await sb.from('workbooks').insert({title:first.workbook_title,subject:first.subject,grade:Number(first.grade),term:Number(first.term),description:first.description||null,active:true,archived:false,created_by:currentTeacher.user_id}).select().single();if(error)throw error;for(const r of group){const ins=await sb.from('activities').insert({workbook_id:w.id,unit:r.unit||null,title:r.activity_title,instructions:r.instructions||null,total_marks:Number(r.total_marks||0),date_loaded:r.date_loaded||todayISO(),due_date:r.due_date||null,questions:(r.questions_pipe||'').split('|').map(x=>x.trim()).filter(Boolean),memo:(r.memo_pipe||'').split('|').map(x=>x.trim()).filter(Boolean),memo_released:String(r.memo_released).toLowerCase()==='true',created_by:currentTeacher.user_id});if(ins.error)throw ins.error;}}toast('CSV workbooks imported.');pageWorkbooks();}catch(e){toast(e.message,true);}finally{setBusy(btn,false);}}
function parseCSV(text){const lines=[];let row=[],field='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){field+='"';i++;}else if(c==='"'){q=!q;}else if(c===','&&!q){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(x=>x!==''))lines.push(row);row=[];field='';}else field+=c;}row.push(field);if(row.some(x=>x!==''))lines.push(row);if(lines.length<2)return[];const h=lines[0].map(x=>x.trim());return lines.slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]||'').trim()])));}
async function fullBackup(btn){setBusy(btn,true,'Building backup…');try{const tables=['teacher_profiles','teacher_access_links','students','workbooks','workbook_assignments','activities','activity_files','submissions','submission_files','corrected_files'];const backup={format:'snt-full-backup-v1',exported_at:new Date().toISOString(),tables:{}};for(const t of tables){const {data,error}=await sb.from(t).select('*');if(error)throw error;backup.tables[t]=data||[];}const zip=new JSZip();zip.file('backup.json',JSON.stringify(backup,null,2));const paths=[...backup.tables.activity_files,...backup.tables.submission_files,...backup.tables.corrected_files].filter(f=>f.storage_path);let i=0;for(const f of paths){i++;btn.textContent=`Files ${i}/${paths.length}`;try{const url=await signed(f.storage_path,1800);zip.file(`storage/${f.storage_path}`,await (await fetch(url)).blob());}catch(e){console.warn('Backup skipped file',f.storage_path,e);}}btn.textContent='Compressing…';downloadBlob(await zip.generateAsync({type:'blob'}),`SNT_Workbook_Hub_Full_Backup_${todayISO()}.zip`);toast('Full backup created.');}catch(e){toast(e.message,true);}finally{setBusy(btn,false);}}

function modal(html){let old=$('.modal-backdrop');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop"><div class="modal">${html}</div></div>`);$$('[data-close]').forEach(b=>b.onclick=closeModal);$('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))closeModal();};}
function closeModal(){ $('.modal-backdrop')?.remove(); }

// ---------- Student portal (no sign-in) ----------
async function studentApi(action,payload={},file=null){
  const url=`${cfg.SUPABASE_URL}/functions/v1/student-api?action=${encodeURIComponent(action)}`;
  const headers={'x-student-token':studentToken,'apikey':cfg.SUPABASE_PUBLISHABLE_KEY}; let body;
  if(file){body=new FormData();body.append('activity_id',payload.activity_id);body.append('file',file);}
  else{headers['Content-Type']='application/json';body=JSON.stringify(payload);}
  let res; try{res=await fetch(url,{method:'POST',headers,body});}catch(err){throw new Error('Cannot reach the learner service. Deploy the Supabase student-api Edge Function with --no-verify-jwt, then try this link again.');} const text=await res.text(); let data={}; try{data=text?JSON.parse(text):{};}catch{data={error:text};} if(!res.ok)throw new Error(data.error||`Learner service request failed (${res.status})`); return data;
}
async function startStudent(){
  try{studentHubCache=await studentApi('hub');renderStudentHub(studentHubCache);}catch(e){app.innerHTML=`<div class="login"><div class="login-card"><div class="login-logo">SNT</div><h1>Private workbook link</h1><div class="error-box">${esc(e.message)}</div><p class="muted">Ask your teacher for a new workbook link if this one has expired or was replaced.</p></div></div>`;}
}
function renderStudentHub(hub){
  const s=hub.student,books=hub.workbooks||[]; const allActs=books.flatMap(b=>b.activities||[]),done=allActs.filter(a=>a.submission).length,pct=allActs.length?Math.round(done/allActs.length*100):0;
  app.innerHTML=`<div class="student-page"><div class="student-shell"><section class="student-hero"><div class="small">${esc(cfg.APP_NAME||'SNT Workbook Hub')}</div><h1>Welcome, ${esc(s.name)}</h1><div>Grade ${s.grade} · ${done}/${allActs.length} activities submitted</div><div class="progress" style="margin-top:.7rem;background:#ffffff44"><span style="width:${pct}%;background:#fff"></span></div><div class="student-filters"><select id="studentTerm"><option value="">All terms</option>${[1,2,3,4].map(t=>`<option value="${t}">Term ${t}</option>`).join('')}</select><select id="studentSubject"><option value="">All subjects</option>${[...new Set(books.map(b=>b.subject))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}</select></div></section><div id="studentBooks" class="stack">${books.map(studentBookCard).join('')||'<div class="empty">No workbooks have been assigned to you yet.</div>'}</div><p class="small muted" style="text-align:center;margin:1.5rem">Keep this private link safe. It opens your own workbook hub.</p></div></div>`;
  const filter=()=>{const t=$('#studentTerm').value,sub=$('#studentSubject').value;$$('[data-student-book]').forEach(c=>c.classList.toggle('hidden',!((!t||c.dataset.term===t)&&(!sub||c.dataset.subject===sub))));};$('#studentTerm').onchange=filter;$('#studentSubject').onchange=filter;
  $$('[data-open-activity]').forEach(b=>b.onclick=()=>{const book=books.find(x=>x.id===b.dataset.book);const a=book.activities.find(x=>x.id===b.dataset.openActivity);studentActivityModal(book,a);});
}
function studentBookCard(b){const acts=b.activities||[],done=acts.filter(a=>a.submission).length;return `<div class="card" data-student-book data-term="${b.term}" data-subject="${esc(b.subject)}"><div class="row spread"><div><div class="small muted">${esc(b.subject)} · Grade ${b.grade}</div><div class="workbook-title">${esc(b.title)}</div></div><div class="row"><span class="pill blue">Term ${b.term}</span>${b.personalized?'<span class="pill green">Personalized for you</span>':''}</div></div><p class="muted">${esc(b.description||'')}</p><div class="progress"><span style="width:${acts.length?Math.round(done/acts.length*100):0}%"></span></div><div class="small muted" style="margin:.35rem 0 .75rem">${done} of ${acts.length} submitted</div><div class="stack">${acts.map(a=>`<div class="activity ${isOverdue(a.due_date)&&!a.submission?'overdue':''}"><div class="row spread"><div><strong>${esc(a.title)}</strong><div class="small muted">${esc(a.unit||'')}</div></div>${a.submission?statusPill(a.submission.status):(isOverdue(a.due_date)?'<span class="pill red">Overdue</span>':'<span class="pill">Not submitted</span>')}</div><div class="small"><span>Loaded ${fmtDate(a.date_loaded)}</span> · <span class="due ${isOverdue(a.due_date)&&!a.submission?'overdue':''}">Due ${fmtDate(a.due_date)}</span></div><button class="btn sm" style="margin-top:.6rem" data-open-activity="${a.id}" data-book="${b.id}">${a.submission?'Open activity':'Do activity'}</button></div>`).join('')||'<div class="muted">No activities yet.</div>'}</div></div>`;}
function studentActivityModal(book,a){
  const sub=a.submission;
  const savedAnswers=Array.isArray(sub?.typed_answers)?sub.typed_answers:[];
  const onlineAnswerFields=(a.questions||[]).length
    ? `<div class="online-answer-list">${(a.questions||[]).map((q,i)=>`<div class="online-answer-item"><div class="online-answer-question"><strong>${i+1}.</strong> ${linkify(q)}</div><textarea data-typed-answer="${i}" placeholder="Type answer ${i+1} here…">${esc(savedAnswers[i]||'')}</textarea></div>`).join('')}</div>`
    : `<div class="field"><label>Your typed answer</label><textarea data-typed-answer="0" placeholder="Type your answer here…">${esc(savedAnswers[0]||'')}</textarea></div>`;
  modal(`<div class="row spread"><div><div class="small muted">${esc(book.subject)} · ${esc(book.title)}</div><h2 style="margin:.15rem 0">${esc(a.title)}</h2></div><button type="button" class="btn secondary sm" data-close>Close</button></div><div class="row small"><span class="pill">Loaded ${fmtDate(a.date_loaded)}</span><span class="pill ${isOverdue(a.due_date)&&!sub?'red':''}">Due ${fmtDate(a.due_date)}</span><span class="pill">${a.total_marks||0} marks</span></div><h3>Instructions</h3><p>${linkifyNl2br(a.instructions||'Answer online, or write the answers in your book and upload your pages below.')}</p><h3>Questions</h3><ol class="question-list">${(a.questions||[]).map(q=>`<li>${linkify(q)}</li>`).join('')}</ol>${studentAttachments(a.question_files,'Question attachment')}<hr style="border:0;border-top:1px solid var(--line);margin:1rem 0"><h3>Your work</h3>${sub?`<div class="info-box">${statusPill(sub.status)} Submitted ${fmtDateTime(sub.submitted_at)}${sub.score!=null?` · <strong>${sub.score}/${a.total_marks} (${moneylessPercent(sub.score,a.total_marks)}%)</strong>`:''}</div>${sub.teacher_comment?`<p><strong>Teacher comment:</strong> ${nl2br(sub.teacher_comment)}</p>`:''}${studentAttachments(sub.files,'Your uploaded page')}${studentAttachments(sub.corrected_files,'Corrected work')}`:'<p class="muted">You may <strong>type your answers online</strong>, upload handwritten pages, or use both.</p>'}<form id="studentUploadForm"><div class="online-answer-box"><div class="row spread"><div><h3 style="margin:.1rem 0">⌨️ Type answers online</h3><div class="hint">You can type directly here instead of uploading handwritten pages, or do both.</div></div><span class="pill blue">Optional</span></div>${onlineAnswerFields}</div><div class="upload-or"><span>OR / AND</span></div><div class="field"><label>${sub?'Add / resubmit handwritten pages':'Upload handwritten pages'}</label><input type="file" name="files" multiple accept="image/*,application/pdf"><div class="hint">Gallery/files: choose multiple images or PDFs.</div><input type="file" name="camera" accept="image/*" capture="environment"><div class="hint">Camera: add one fresh photo. You can submit typed answers and files together.</div></div><div class="modal-actions"><button class="btn">${sub?'Submit updated answers':'Submit answers'}</button></div></form>${a.memo_released?`<hr style="border:0;border-top:1px solid var(--line);margin:1rem 0"><h3>✅ Memo released</h3><ol class="question-list">${(a.memo||[]).map(x=>`<li>${linkify(x)}</li>`).join('')}</ol>${studentAttachments(a.memo_files,'Memo attachment')}`:'<div class="info-box">🔒 The memo is hidden until your teacher releases it.</div>'}`);
  $('#studentUploadForm').onsubmit=async e=>{
    e.preventDefault();
    const form=e.currentTarget;
    const btn=e.submitter;
    const files=[...form.elements.files.files,...form.elements.camera.files];
    const typedAnswers=$$('[data-typed-answer]',form).sort((x,y)=>Number(x.dataset.typedAnswer)-Number(y.dataset.typedAnswer)).map(x=>x.value);
    const hasTyped=typedAnswers.some(x=>x.trim());
    if(!files.length&&!hasTyped)return toast('Type at least one answer or choose an image/PDF.',true);
    setBusy(btn,true,files.length?'Uploading…':'Submitting…');
    try{
      for(let i=0;i<files.length;i++){
        btn.textContent=`Uploading ${i+1}/${files.length}`;
        await studentApi('upload',{activity_id:a.id},files[i]);
      }
      btn.textContent='Submitting…';
      await studentApi('submit',{activity_id:a.id,typed_answers:typedAnswers});
      studentHubCache=await studentApi('hub');
      closeModal();
      renderStudentHub(studentHubCache);
      toast('Answers submitted successfully.');
    }catch(err){setBusy(btn,false);toast(err.message,true);}
  };
}

function studentAttachments(files,label){if(!files?.length)return'';return `<div class="attachment-grid" style="margin-top:.7rem">${files.map(f=>`<div class="attachment">${!f.external_url&&f.mime_type?.startsWith('image/')?`<img src="${esc(f.url)}" alt="${esc(label)}">`:''}<a href="${esc(f.url)}" target="_blank" rel="noopener noreferrer">${f.external_url?'🌐':'📎'} ${esc(f.file_name)}</a></div>`).join('')}</div>`;}

async function teacherLinkLogin(){
  const {data:{session}}=await sb.auth.getSession();
  if(session){ const u=new URL(location.href);u.searchParams.delete(cfg.TEACHER_LINK_PARAM||'teacher');if(u.hash.startsWith('#teacher='))u.hash='';history.replaceState({},'',u.pathname+u.search+u.hash);return startTeacher(); }
  try{
    let res;try{res=await fetch(`${cfg.SUPABASE_URL}/functions/v1/teacher-link`,{method:'POST',headers:{'x-teacher-token':teacherLinkToken,'x-site-url':location.origin+location.pathname,'apikey':cfg.SUPABASE_PUBLISHABLE_KEY}});}catch{throw new Error('Cannot reach the teacher-link service. Deploy the Supabase teacher-link Edge Function with --no-verify-jwt.');}
    const data=await res.json();if(!res.ok)throw new Error(data.error||'Teacher link failed.');
    location.replace(data.action_link);
  }catch(e){app.innerHTML=`<div class="login"><div class="login-card"><div class="login-logo">SNT</div><h1>Teacher link</h1><div class="error-box">${esc(e.message)}</div></div></div>`;}
}
async function boot(){ if(!configured)return setupScreen(); if(studentToken)return startStudent(); if(teacherLinkToken)return teacherLinkLogin(); return startTeacher(); }
boot();

